package cz.bbn.cerberus.ares.dto;

import java.util.HashMap;
import java.util.Map;

public class LawForm {

    public static final Map<String, String> LAW_FORM_MAP = new HashMap<>() {{
        put("100", "Podnikající osoba tuzemská");
        put("101", "Fyzická osoba podnikající dle živnostenského zákona");
        put("102", "Fyzická osoba podnikající dle živnostenského zákona zapsaná v obchodním rejstříku");
        put("104", "Samostatně hospodařící rolník zapsaný v obchodním rejstříku");
        put("105", "Fyzická osoba podnikající dle jiných zákonů než živnostenského a zákona o zemědělství");
        put("106", "Fyzická osoba podnikající dle jiných zákonů než živnostenského a zákona o zemědělství zapsaná v obchodním rejstříku");
        put("107", "Zemědělský podnikatel - fyzická osoba");
        put("108", "Zemědělský podnikatel - fyzická osoba zapsaná v obchodním rejstříku");
        put("111", "Veřejná obchodní společnost");
        put("112", "Společnost s ručením omezeným");
        put("113", "Společnost komanditní");
        put("115", "Společný podnik");
        put("116", "Zájmové sdružení");
        put("117", "Nadace");
        put("118", "Nadační fond");
        put("121", "Akciová společnost");
        put("141", "Obecně prospěšná společnost");
        put("145", "Společenství vlastníků jednotek");
        put("151", "Komoditní burza");
        put("152", "Garanční fond obchodníků s cennými papíry");
        put("161", "Ústav");
        put("201", "Zemědělské družstvo");
        put("205", "Družstvo");
        put("231", "Výrobní družstvo");
        put("232", "Spotřební družstvo");
        put("233", "Bytové družstvo");
        put("234", "Jiné družstvo");
        put("241", "Družstevní podnik (s jedním zakladatelem)");
        put("242", "Společný podnik (s více zakladateli)");
        put("put(\"251", "Zájmová organizace družstev");
        put("261", "Společná zájmová organizace družstev");
        put("301", "Státní podnik");
        put("302", "Národní podnik");
        put("312", "Banka-státní peněžní ústav");
        put("313", "Česká národní banka");
        put("314", "Česká konsolidační agentura");
        put("325", "Organizační složka státu");
        put("331", "Příspěvková organizace");
        put("332", "Státní příspěvková organizace");
        put("352", "Státní organizace Správa železnic");
        put("353", "Rada pro veřejný dohled nad auditem");
        put("361", "Veřejnoprávní instituce (ČT,ČRo,ČTK)");
        put("362", "Česká tisková kancelář");
        put("381", "Fond (ze zákona)");
        put("382", "Státní fond ze zákona");
        put("391", "Zdravotní pojišťovna");
        put("401", "Sdružení mezinárodního obchodu");
        put("411", "Podnik se zahraniční majetkovou účastí");
        put("421", "Odštěpný závod zahraniční právnické osoby");
        put("422", "Organizační složka zahraničního nadačního fondu");
        put("423", "Organizační složka zahraniční nadace");
        put("424", "Zahraniční");
        put("425", "Odštěpný závod zahraniční fyzické osoby");
        put("426", "Zastoupení zahraniční banky");
        put("441", "Podnik zahraničního obchodu");
        put("501", "Odštěpný závod nebo jiná organizační složka podniku zapisující se do obchodního rejstříku");
        put("521", "Samostatná drobná provozovna obecního úřadu");
        put("525", "Vnitřní organizační jednotka organizační složky státu");
        put("541", "Podílový fond");
        put("601", "Vysoká škola");
        put("641", "Školská právnická osoba");
        put("651", "Zdravotnické zařízení");
        put("661", "Veřejná výzkumná instituce");
        put("671", "Veřejné neziskové ústavní zdravotnické zařízení");
        put("701", "Sdružení (svaz, spolek, společnost, klub aj.)");
        put("703", "Odborová organizace a organizace zaměstnavatelů");
        put("704", "Zvláštní organizace pro zastoupení českých zájmů v mezinárodních nevládních organizacích");
        put("705", "Podnik nebo hospodářské zařízení sdružení");
        put("706", "Spolek");
        put("707", "Odborová organizace");
        put("708", "Organizace zaměstnavatelů");
        put("711", "Politická strana, politické hnutí");
        put("715", "Podnik nebo hospodářské zařízení politické strany");
        put("721", "Církevní organizace");
        put("722", "Evidované církevní právnické osoby");
        put("723", "Svazy církví a náboženských společností");
        put("731", "Organizační jednotka sdružení");
        put("732", "Organizační jednotka politické strany, politického hnutí");
        put("733", "Organizační jednotka odborové organizace a organizace zaměstnavatelů");
        put("736", "Pobočný spolek");
        put("741", "Stavovská organizace - profesní komora");
        put("745", "Komora (s výjimkou profesních komor)");
        put("751", "Zájmové sdružení právnických osob");
        put("761", "Honební společenstvo");
        put("771", "Svazek obcí");
        put("801", "Obec nebo městská část hlavního města Prahy");
        put("804", "Kraj");
        put("805", "Regionální rada regionu soudržnosti");
        put("811", "Městská část, městský obvod");
        put("901", "Zastupitelský orgán jiných států");
        put("906", "Zahraniční spolek");
        put("907", "Mezinárodní odborová organizace");
        put("908", "Mezinárodní organizace zaměstnavatelů");
        put("911", "Zahraniční kulturní, informační středisko, rozhlasová, tisková a televizní agentura");
        put("921", "Mezinárodní organizace a sdružení");
        put("922", "Organizační jednotka organizace s mezinárodním prvkem");
        put("931", "Evropské hospodářské zájmové sdružení");
        put("932", "Evropská společnost");
        put("933", "Evropská družstevní společnost");
        put("936", "Zahraniční pobočný spolek");
        put("937", "Pobočná mezinárodní odborová organizace");
        put("938", "Pobočná mezinárodní organizace zaměstnavatelů");
        put("941", "Evropské seskupení pro územní spolupráci");
        put("950", "Subjekt právním řádem výslovně neupravený");
        put("951", "Mezinárodní vojenská organizace vzniklá na základě mezinárodní smlouvy");
        put("952", "Konsorcium evropské výzkumné infrastruktury");
        put("960", "Právnická osoba zřízená zvláštním zákonem zapisovaná do veřejného rejstříku");
        put("961", "Svěřenský fond");
        put("962", "Zahraniční svěřenský fond");
    }};
}
