//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intrastatItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="intrastatItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="goodsCode" type="{http://www.stormware.cz/schema/version_2/type.xsd}string8" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.stormware.cz/schema/version_2/type.xsd}string255" minOccurs="0"/&gt;
 *         &lt;element name="countryOfDestination" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="countryOfDispatch" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="countryOfOrigin" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="region" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="invoicedAmount" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="transportExpenses" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="ownWeight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="addUnit" type="{http://www.stormware.cz/schema/version_2/type.xsd}string3" minOccurs="0"/&gt;
 *         &lt;element name="transaction" type="{http://www.stormware.cz/schema/version_2/type.xsd}string3" minOccurs="0"/&gt;
 *         &lt;element name="termsOfDelivery" type="{http://www.stormware.cz/schema/version_2/type.xsd}string3" minOccurs="0"/&gt;
 *         &lt;element name="modeOfTransport" type="{http://www.stormware.cz/schema/version_2/type.xsd}string1" minOccurs="0"/&gt;
 *         &lt;element name="statisticalCode" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="specialTransaction" type="{http://www.stormware.cz/schema/version_2/type.xsd}string2" minOccurs="0"/&gt;
 *         &lt;element name="VATIdOfPartner" type="{http://www.stormware.cz/schema/version_2/type.xsd}dicType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "intrastatItemType", propOrder = {

})
public class IntrastatItemType {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    protected String goodsCode;
    protected String description;
    protected String countryOfDestination;
    protected String countryOfDispatch;
    protected String countryOfOrigin;
    protected String region;
    protected Double invoicedAmount;
    protected Double transportExpenses;
    @XmlElement(defaultValue = "0")
    protected Float ownWeight;
    protected Float quantity;
    protected String addUnit;
    protected String transaction;
    protected String termsOfDelivery;
    protected String modeOfTransport;
    protected String statisticalCode;
    protected String specialTransaction;
    @XmlElement(name = "VATIdOfPartner")
    protected String vatIdOfPartner;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the goodsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * Sets the value of the goodsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsCode(String value) {
        this.goodsCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the countryOfDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfDestination() {
        return countryOfDestination;
    }

    /**
     * Sets the value of the countryOfDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfDestination(String value) {
        this.countryOfDestination = value;
    }

    /**
     * Gets the value of the countryOfDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfDispatch() {
        return countryOfDispatch;
    }

    /**
     * Sets the value of the countryOfDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfDispatch(String value) {
        this.countryOfDispatch = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the invoicedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInvoicedAmount() {
        return invoicedAmount;
    }

    /**
     * Sets the value of the invoicedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInvoicedAmount(Double value) {
        this.invoicedAmount = value;
    }

    /**
     * Gets the value of the transportExpenses property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransportExpenses() {
        return transportExpenses;
    }

    /**
     * Sets the value of the transportExpenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransportExpenses(Double value) {
        this.transportExpenses = value;
    }

    /**
     * Gets the value of the ownWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOwnWeight() {
        return ownWeight;
    }

    /**
     * Sets the value of the ownWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOwnWeight(Float value) {
        this.ownWeight = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setQuantity(Float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the addUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddUnit() {
        return addUnit;
    }

    /**
     * Sets the value of the addUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddUnit(String value) {
        this.addUnit = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransaction(String value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the termsOfDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsOfDelivery() {
        return termsOfDelivery;
    }

    /**
     * Sets the value of the termsOfDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsOfDelivery(String value) {
        this.termsOfDelivery = value;
    }

    /**
     * Gets the value of the modeOfTransport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeOfTransport() {
        return modeOfTransport;
    }

    /**
     * Sets the value of the modeOfTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeOfTransport(String value) {
        this.modeOfTransport = value;
    }

    /**
     * Gets the value of the statisticalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatisticalCode() {
        return statisticalCode;
    }

    /**
     * Sets the value of the statisticalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatisticalCode(String value) {
        this.statisticalCode = value;
    }

    /**
     * Gets the value of the specialTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialTransaction() {
        return specialTransaction;
    }

    /**
     * Sets the value of the specialTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialTransaction(String value) {
        this.specialTransaction = value;
    }

    /**
     * Gets the value of the vatIdOfPartner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVATIdOfPartner() {
        return vatIdOfPartner;
    }

    /**
     * Sets the value of the vatIdOfPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVATIdOfPartner(String value) {
        this.vatIdOfPartner = value;
    }

}
