//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import cz.stormware.schema.version_2.print.AgendaPrintType;
import cz.stormware.schema.version_2.type.CancelDocumentType;
import cz.stormware.schema.version_2.type.CorrectiveDocumentType;
import cz.stormware.schema.version_2.type.EETType;
import cz.stormware.schema.version_2.type.LinksType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="links" type="{http://www.stormware.cz/schema/version_2/type.xsd}linksType" minOccurs="0"/&gt;
 *         &lt;element name="cancelDocument" type="{http://www.stormware.cz/schema/version_2/type.xsd}cancelDocumentType" minOccurs="0"/&gt;
 *         &lt;element name="correctiveDocument" type="{http://www.stormware.cz/schema/version_2/type.xsd}correctiveDocumentType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceHeader" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceHeaderType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceRetentions" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceRetentionsType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceDetail" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceDetailType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceSummary" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceSummaryType" minOccurs="0"/&gt;
 *         &lt;element name="linkedDocuments" type="{http://www.stormware.cz/schema/version_2/type.xsd}linksType" minOccurs="0"/&gt;
 *         &lt;element name="EET" type="{http://www.stormware.cz/schema/version_2/type.xsd}EETType" minOccurs="0"/&gt;
 *         &lt;element name="print" type="{http://www.stormware.cz/schema/version_2/print.xsd}agendaPrintType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invVersionType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceType", propOrder = {
    "links",
    "cancelDocument",
    "correctiveDocument",
    "invoiceHeader",
    "invoiceRetentions",
    "invoiceDetail",
    "invoiceSummary",
    "linkedDocuments",
    "eet",
    "print"
})
public class InvoiceType {

    protected LinksType links;
    protected CancelDocumentType cancelDocument;
    protected CorrectiveDocumentType correctiveDocument;
    protected InvoiceHeaderType invoiceHeader;
    protected InvoiceRetentionsType invoiceRetentions;
    protected InvoiceDetailType invoiceDetail;
    protected InvoiceSummaryType invoiceSummary;
    protected LinksType linkedDocuments;
    @XmlElement(name = "EET")
    protected EETType eet;
    protected AgendaPrintType print;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link LinksType }
     *     
     */
    public LinksType getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksType }
     *     
     */
    public void setLinks(LinksType value) {
        this.links = value;
    }

    /**
     * Gets the value of the cancelDocument property.
     * 
     * @return
     *     possible object is
     *     {@link CancelDocumentType }
     *     
     */
    public CancelDocumentType getCancelDocument() {
        return cancelDocument;
    }

    /**
     * Sets the value of the cancelDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelDocumentType }
     *     
     */
    public void setCancelDocument(CancelDocumentType value) {
        this.cancelDocument = value;
    }

    /**
     * Gets the value of the correctiveDocument property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectiveDocumentType }
     *     
     */
    public CorrectiveDocumentType getCorrectiveDocument() {
        return correctiveDocument;
    }

    /**
     * Sets the value of the correctiveDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectiveDocumentType }
     *     
     */
    public void setCorrectiveDocument(CorrectiveDocumentType value) {
        this.correctiveDocument = value;
    }

    /**
     * Gets the value of the invoiceHeader property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceHeaderType }
     *     
     */
    public InvoiceHeaderType getInvoiceHeader() {
        return invoiceHeader;
    }

    /**
     * Sets the value of the invoiceHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceHeaderType }
     *     
     */
    public void setInvoiceHeader(InvoiceHeaderType value) {
        this.invoiceHeader = value;
    }

    /**
     * Gets the value of the invoiceRetentions property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceRetentionsType }
     *     
     */
    public InvoiceRetentionsType getInvoiceRetentions() {
        return invoiceRetentions;
    }

    /**
     * Sets the value of the invoiceRetentions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceRetentionsType }
     *     
     */
    public void setInvoiceRetentions(InvoiceRetentionsType value) {
        this.invoiceRetentions = value;
    }

    /**
     * Gets the value of the invoiceDetail property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetailType }
     *     
     */
    public InvoiceDetailType getInvoiceDetail() {
        return invoiceDetail;
    }

    /**
     * Sets the value of the invoiceDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetailType }
     *     
     */
    public void setInvoiceDetail(InvoiceDetailType value) {
        this.invoiceDetail = value;
    }

    /**
     * Gets the value of the invoiceSummary property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceSummaryType }
     *     
     */
    public InvoiceSummaryType getInvoiceSummary() {
        return invoiceSummary;
    }

    /**
     * Sets the value of the invoiceSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceSummaryType }
     *     
     */
    public void setInvoiceSummary(InvoiceSummaryType value) {
        this.invoiceSummary = value;
    }

    /**
     * Gets the value of the linkedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link LinksType }
     *     
     */
    public LinksType getLinkedDocuments() {
        return linkedDocuments;
    }

    /**
     * Sets the value of the linkedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinksType }
     *     
     */
    public void setLinkedDocuments(LinksType value) {
        this.linkedDocuments = value;
    }

    /**
     * Gets the value of the eet property.
     * 
     * @return
     *     possible object is
     *     {@link EETType }
     *     
     */
    public EETType getEET() {
        return eet;
    }

    /**
     * Sets the value of the eet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EETType }
     *     
     */
    public void setEET(EETType value) {
        this.eet = value;
    }

    /**
     * Gets the value of the print property.
     * 
     * @return
     *     possible object is
     *     {@link AgendaPrintType }
     *     
     */
    public AgendaPrintType getPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgendaPrintType }
     *     
     */
    public void setPrint(AgendaPrintType value) {
        this.print = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
