//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import java.math.BigInteger;
import cz.stormware.schema.version_2.type.ClassificationVATType;
import cz.stormware.schema.version_2.type.EETItemType;
import cz.stormware.schema.version_2.type.GuaranteeTypeType;
import cz.stormware.schema.version_2.type.LinkItemType;
import cz.stormware.schema.version_2.type.LinkToStockType;
import cz.stormware.schema.version_2.type.LinkedDocumentType;
import cz.stormware.schema.version_2.type.MOSStype;
import cz.stormware.schema.version_2.type.ParametersType;
import cz.stormware.schema.version_2.type.RecyclingContribType;
import cz.stormware.schema.version_2.type.RefType;
import cz.stormware.schema.version_2.type.StockItemType;
import cz.stormware.schema.version_2.type.TypeCurrencyForeignItem;
import cz.stormware.schema.version_2.type.TypeCurrencyHomeItem;
import cz.stormware.schema.version_2.type.VatRateType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="link" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkItemType" minOccurs="0"/&gt;
 *         &lt;element name="linkedDocument" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkedDocumentType" minOccurs="0"/&gt;
 *         &lt;element name="id" type="{http://www.stormware.cz/schema/version_2/type.xsd}idType" minOccurs="0"/&gt;
 *         &lt;element name="extId" type="{http://www.stormware.cz/schema/version_2/type.xsd}string64" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.stormware.cz/schema/version_2/type.xsd}string90" minOccurs="0"/&gt;
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="unit" type="{http://www.stormware.cz/schema/version_2/type.xsd}unitType" minOccurs="0"/&gt;
 *         &lt;element name="coefficient" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="payVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *         &lt;element name="rateVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}vatRateType" minOccurs="0"/&gt;
 *         &lt;element name="percentVAT" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="discountPercentage" type="{http://www.stormware.cz/schema/version_2/type.xsd}typePercentage" minOccurs="0"/&gt;
 *         &lt;element name="homeCurrency" type="{http://www.stormware.cz/schema/version_2/type.xsd}typeCurrencyHomeItem" minOccurs="0"/&gt;
 *         &lt;element name="foreignCurrency" type="{http://www.stormware.cz/schema/version_2/type.xsd}typeCurrencyForeignItem" minOccurs="0"/&gt;
 *         &lt;element name="typeServiceMOSS" type="{http://www.stormware.cz/schema/version_2/type.xsd}MOSStype" minOccurs="0"/&gt;
 *         &lt;element name="note" type="{http://www.stormware.cz/schema/version_2/type.xsd}string90" minOccurs="0"/&gt;
 *         &lt;element name="code" type="{http://www.stormware.cz/schema/version_2/type.xsd}stockIdsType" minOccurs="0"/&gt;
 *         &lt;element name="guarantee" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="guaranteeType" type="{http://www.stormware.cz/schema/version_2/type.xsd}guaranteeTypeType" minOccurs="0"/&gt;
 *         &lt;element name="stockItem" type="{http://www.stormware.cz/schema/version_2/type.xsd}stockItemType" minOccurs="0"/&gt;
 *         &lt;element name="linkToStock" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkToStockType" minOccurs="0"/&gt;
 *         &lt;element name="accounting" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="classificationVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}classificationVATType" minOccurs="0"/&gt;
 *         &lt;element name="classificationKVDPH" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="PDP" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CodePDP" type="{http://www.stormware.cz/schema/version_2/type.xsd}string4" minOccurs="0"/&gt;
 *         &lt;element name="recyclingContrib" type="{http://www.stormware.cz/schema/version_2/type.xsd}recyclingContribType" minOccurs="0"/&gt;
 *         &lt;element name="centre" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="activity" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="contract" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="expirationDate" type="{http://www.stormware.cz/schema/version_2/type.xsd}dateOrNull" minOccurs="0"/&gt;
 *         &lt;element name="intrastatItem" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}intrastatItemType" minOccurs="0"/&gt;
 *         &lt;element name="EETItem" type="{http://www.stormware.cz/schema/version_2/type.xsd}EETItemType" minOccurs="0"/&gt;
 *         &lt;element name="parameters" type="{http://www.stormware.cz/schema/version_2/type.xsd}parametersType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceItemType", propOrder = {

})
public class InvoiceItemType {

    protected LinkItemType link;
    protected LinkedDocumentType linkedDocument;
    protected BigInteger id;
    protected String extId;
    protected String text;
    protected Float quantity;
    protected String unit;
    @XmlElement(defaultValue = "1.0")
    protected Float coefficient;
    @XmlElement(defaultValue = "false")
    @XmlSchemaType(name = "string")
    protected cz.stormware.schema.version_2.type.Boolean payVAT;
    @XmlElement(defaultValue = "none")
    @XmlSchemaType(name = "string")
    protected VatRateType rateVAT;
    protected Float percentVAT;
    @XmlElement(defaultValue = "0")
    protected Float discountPercentage;
    protected TypeCurrencyHomeItem homeCurrency;
    protected TypeCurrencyForeignItem foreignCurrency;
    protected MOSStype typeServiceMOSS;
    protected String note;
    protected String code;
    protected BigInteger guarantee;
    @XmlSchemaType(name = "string")
    protected GuaranteeTypeType guaranteeType;
    protected StockItemType stockItem;
    protected LinkToStockType linkToStock;
    protected RefType accounting;
    protected ClassificationVATType classificationVAT;
    protected RefType classificationKVDPH;
    @XmlElement(name = "PDP")
    protected java.lang.Boolean pdp;
    @XmlElement(name = "CodePDP")
    protected String codePDP;
    protected RecyclingContribType recyclingContrib;
    protected RefType centre;
    protected RefType activity;
    protected RefType contract;
    protected String expirationDate;
    protected IntrastatItemType intrastatItem;
    @XmlElement(name = "EETItem")
    @XmlSchemaType(name = "string")
    protected EETItemType eetItem;
    protected ParametersType parameters;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkItemType }
     *     
     */
    public LinkItemType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkItemType }
     *     
     */
    public void setLink(LinkItemType value) {
        this.link = value;
    }

    /**
     * Gets the value of the linkedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedDocumentType }
     *     
     */
    public LinkedDocumentType getLinkedDocument() {
        return linkedDocument;
    }

    /**
     * Sets the value of the linkedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedDocumentType }
     *     
     */
    public void setLinkedDocument(LinkedDocumentType value) {
        this.linkedDocument = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the extId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtId() {
        return extId;
    }

    /**
     * Sets the value of the extId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtId(String value) {
        this.extId = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setQuantity(Float value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the coefficient property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getCoefficient() {
        return coefficient;
    }

    /**
     * Sets the value of the coefficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setCoefficient(Float value) {
        this.coefficient = value;
    }

    /**
     * Gets the value of the payVAT property.
     * 
     * @return
     *     possible object is
     *     {@link cz.stormware.schema.version_2.type.Boolean }
     *     
     */
    public cz.stormware.schema.version_2.type.Boolean getPayVAT() {
        return payVAT;
    }

    /**
     * Sets the value of the payVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link cz.stormware.schema.version_2.type.Boolean }
     *     
     */
    public void setPayVAT(cz.stormware.schema.version_2.type.Boolean value) {
        this.payVAT = value;
    }

    /**
     * Gets the value of the rateVAT property.
     * 
     * @return
     *     possible object is
     *     {@link VatRateType }
     *     
     */
    public VatRateType getRateVAT() {
        return rateVAT;
    }

    /**
     * Sets the value of the rateVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link VatRateType }
     *     
     */
    public void setRateVAT(VatRateType value) {
        this.rateVAT = value;
    }

    /**
     * Gets the value of the percentVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPercentVAT() {
        return percentVAT;
    }

    /**
     * Sets the value of the percentVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPercentVAT(Float value) {
        this.percentVAT = value;
    }

    /**
     * Gets the value of the discountPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDiscountPercentage() {
        return discountPercentage;
    }

    /**
     * Sets the value of the discountPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDiscountPercentage(Float value) {
        this.discountPercentage = value;
    }

    /**
     * Gets the value of the homeCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCurrencyHomeItem }
     *     
     */
    public TypeCurrencyHomeItem getHomeCurrency() {
        return homeCurrency;
    }

    /**
     * Sets the value of the homeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCurrencyHomeItem }
     *     
     */
    public void setHomeCurrency(TypeCurrencyHomeItem value) {
        this.homeCurrency = value;
    }

    /**
     * Gets the value of the foreignCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCurrencyForeignItem }
     *     
     */
    public TypeCurrencyForeignItem getForeignCurrency() {
        return foreignCurrency;
    }

    /**
     * Sets the value of the foreignCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCurrencyForeignItem }
     *     
     */
    public void setForeignCurrency(TypeCurrencyForeignItem value) {
        this.foreignCurrency = value;
    }

    /**
     * Gets the value of the typeServiceMOSS property.
     * 
     * @return
     *     possible object is
     *     {@link MOSStype }
     *     
     */
    public MOSStype getTypeServiceMOSS() {
        return typeServiceMOSS;
    }

    /**
     * Sets the value of the typeServiceMOSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link MOSStype }
     *     
     */
    public void setTypeServiceMOSS(MOSStype value) {
        this.typeServiceMOSS = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the guarantee property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGuarantee() {
        return guarantee;
    }

    /**
     * Sets the value of the guarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGuarantee(BigInteger value) {
        this.guarantee = value;
    }

    /**
     * Gets the value of the guaranteeType property.
     * 
     * @return
     *     possible object is
     *     {@link GuaranteeTypeType }
     *     
     */
    public GuaranteeTypeType getGuaranteeType() {
        return guaranteeType;
    }

    /**
     * Sets the value of the guaranteeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuaranteeTypeType }
     *     
     */
    public void setGuaranteeType(GuaranteeTypeType value) {
        this.guaranteeType = value;
    }

    /**
     * Gets the value of the stockItem property.
     * 
     * @return
     *     possible object is
     *     {@link StockItemType }
     *     
     */
    public StockItemType getStockItem() {
        return stockItem;
    }

    /**
     * Sets the value of the stockItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockItemType }
     *     
     */
    public void setStockItem(StockItemType value) {
        this.stockItem = value;
    }

    /**
     * Gets the value of the linkToStock property.
     * 
     * @return
     *     possible object is
     *     {@link LinkToStockType }
     *     
     */
    public LinkToStockType getLinkToStock() {
        return linkToStock;
    }

    /**
     * Sets the value of the linkToStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkToStockType }
     *     
     */
    public void setLinkToStock(LinkToStockType value) {
        this.linkToStock = value;
    }

    /**
     * Gets the value of the accounting property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getAccounting() {
        return accounting;
    }

    /**
     * Sets the value of the accounting property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setAccounting(RefType value) {
        this.accounting = value;
    }

    /**
     * Gets the value of the classificationVAT property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationVATType }
     *     
     */
    public ClassificationVATType getClassificationVAT() {
        return classificationVAT;
    }

    /**
     * Sets the value of the classificationVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationVATType }
     *     
     */
    public void setClassificationVAT(ClassificationVATType value) {
        this.classificationVAT = value;
    }

    /**
     * Gets the value of the classificationKVDPH property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getClassificationKVDPH() {
        return classificationKVDPH;
    }

    /**
     * Sets the value of the classificationKVDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setClassificationKVDPH(RefType value) {
        this.classificationKVDPH = value;
    }

    /**
     * Gets the value of the pdp property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public java.lang.Boolean isPDP() {
        return pdp;
    }

    /**
     * Sets the value of the pdp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setPDP(java.lang.Boolean value) {
        this.pdp = value;
    }

    /**
     * Gets the value of the codePDP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePDP() {
        return codePDP;
    }

    /**
     * Sets the value of the codePDP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePDP(String value) {
        this.codePDP = value;
    }

    /**
     * Gets the value of the recyclingContrib property.
     * 
     * @return
     *     possible object is
     *     {@link RecyclingContribType }
     *     
     */
    public RecyclingContribType getRecyclingContrib() {
        return recyclingContrib;
    }

    /**
     * Sets the value of the recyclingContrib property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecyclingContribType }
     *     
     */
    public void setRecyclingContrib(RecyclingContribType value) {
        this.recyclingContrib = value;
    }

    /**
     * Gets the value of the centre property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getCentre() {
        return centre;
    }

    /**
     * Sets the value of the centre property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setCentre(RefType value) {
        this.centre = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setActivity(RefType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setContract(RefType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the intrastatItem property.
     * 
     * @return
     *     possible object is
     *     {@link IntrastatItemType }
     *     
     */
    public IntrastatItemType getIntrastatItem() {
        return intrastatItem;
    }

    /**
     * Sets the value of the intrastatItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntrastatItemType }
     *     
     */
    public void setIntrastatItem(IntrastatItemType value) {
        this.intrastatItem = value;
    }

    /**
     * Gets the value of the eetItem property.
     * 
     * @return
     *     possible object is
     *     {@link EETItemType }
     *     
     */
    public EETItemType getEETItem() {
        return eetItem;
    }

    /**
     * Sets the value of the eetItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link EETItemType }
     *     
     */
    public void setEETItem(EETItemType value) {
        this.eetItem = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersType }
     *     
     */
    public ParametersType getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersType }
     *     
     */
    public void setParameters(ParametersType value) {
        this.parameters = value;
    }

}
