//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import cz.stormware.schema.version_2.type.RoundingItemType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceDetailType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="invoiceItem" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceItemType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="invoiceAdvancePaymentItem" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceAdvancePaymentItemType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="roundingItem" type="{http://www.stormware.cz/schema/version_2/type.xsd}roundingItemType" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceDetailType", propOrder = {
    "content"
})
public class InvoiceDetailType {

    @XmlElementRefs({
        @XmlElementRef(name = "invoiceItem", namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "invoiceAdvancePaymentItem", namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "roundingItem", namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link InvoiceAdvancePaymentItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link InvoiceItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link RoundingItemType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
