//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import cz.stormware.schema.version_2.type.AccountType;
import cz.stormware.schema.version_2.type.AccountingType;
import cz.stormware.schema.version_2.type.Address;
import cz.stormware.schema.version_2.type.Boolean;
import cz.stormware.schema.version_2.type.CarrierType;
import cz.stormware.schema.version_2.type.ClassificationVATType;
import cz.stormware.schema.version_2.type.ExtIdType;
import cz.stormware.schema.version_2.type.LabelsType;
import cz.stormware.schema.version_2.type.LiquidationType;
import cz.stormware.schema.version_2.type.MOSStype;
import cz.stormware.schema.version_2.type.MyAddress;
import cz.stormware.schema.version_2.type.NumberType;
import cz.stormware.schema.version_2.type.ParametersType;
import cz.stormware.schema.version_2.type.PaymentType;
import cz.stormware.schema.version_2.type.RefType;
import cz.stormware.schema.version_2.type.RefTypeRegVATinEU;
import cz.stormware.schema.version_2.type.ResourcesMOSStype;
import cz.stormware.schema.version_2.type.StornoType;
import cz.stormware.schema.version_2.type.TypeValidate;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for invoiceHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceHeaderType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="id" type="{http://www.stormware.cz/schema/version_2/type.xsd}idType" minOccurs="0"/&gt;
 *         &lt;element name="extId" type="{http://www.stormware.cz/schema/version_2/type.xsd}extIdType" minOccurs="0"/&gt;
 *         &lt;element name="invoiceType" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}invoiceTypeType"/&gt;
 *         &lt;element name="storno" type="{http://www.stormware.cz/schema/version_2/type.xsd}stornoType" minOccurs="0"/&gt;
 *         &lt;element name="sphereType" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}sphereTypeType" minOccurs="0"/&gt;
 *         &lt;element name="number" type="{http://www.stormware.cz/schema/version_2/type.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="symVar" type="{http://www.stormware.cz/schema/version_2/type.xsd}symVarType" minOccurs="0"/&gt;
 *         &lt;element name="originalDocument" type="{http://www.stormware.cz/schema/version_2/type.xsd}documentNumberType" minOccurs="0"/&gt;
 *         &lt;element name="originalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="symPar" type="{http://www.stormware.cz/schema/version_2/type.xsd}symVarType" minOccurs="0"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateTax" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateAccounting" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateKHDPH" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateDue" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateApplicationVAT" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="dateDelivery" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="accounting" type="{http://www.stormware.cz/schema/version_2/type.xsd}accountingType" minOccurs="0"/&gt;
 *         &lt;element name="classificationVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}classificationVATType" minOccurs="0"/&gt;
 *         &lt;element name="classificationKVDPH" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="numberKHDPH" type="{http://www.stormware.cz/schema/version_2/type.xsd}string32" minOccurs="0"/&gt;
 *         &lt;element name="numberKVDPH" type="{http://www.stormware.cz/schema/version_2/type.xsd}string32" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.stormware.cz/schema/version_2/type.xsd}string240" minOccurs="0"/&gt;
 *         &lt;element name="partnerIdentity" type="{http://www.stormware.cz/schema/version_2/type.xsd}address" minOccurs="0"/&gt;
 *         &lt;element name="myIdentity" type="{http://www.stormware.cz/schema/version_2/type.xsd}myAddress" minOccurs="0"/&gt;
 *         &lt;element name="order" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="numberOrder" type="{http://www.stormware.cz/schema/version_2/type.xsd}documentNumberType" minOccurs="0"/&gt;
 *         &lt;element name="dateOrder" type="{http://www.stormware.cz/schema/version_2/type.xsd}dateOrNull" minOccurs="0"/&gt;
 *         &lt;element name="priceLevel" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="paymentType" type="{http://www.stormware.cz/schema/version_2/type.xsd}paymentType" minOccurs="0"/&gt;
 *         &lt;element name="account" type="{http://www.stormware.cz/schema/version_2/type.xsd}accountType" minOccurs="0"/&gt;
 *         &lt;element name="symConst" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="symSpec" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="16"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="paymentAccount" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;group ref="{http://www.stormware.cz/schema/version_2/type.xsd}myGroupOfAccount"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="messageForRecipient" type="{http://www.stormware.cz/schema/version_2/type.xsd}string35" minOccurs="0"/&gt;
 *         &lt;element name="dateOfPaymentOrder" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="paymentTerminal" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *         &lt;element name="centre" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="activity" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="contract" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="regVATinEU" type="{http://www.stormware.cz/schema/version_2/type.xsd}refTypeRegVATinEU" minOccurs="0"/&gt;
 *         &lt;element name="MOSS" type="{http://www.stormware.cz/schema/version_2/type.xsd}MOSStype" minOccurs="0"/&gt;
 *         &lt;element name="evidentiaryResourcesMOSS" type="{http://www.stormware.cz/schema/version_2/type.xsd}resourcesMOSStype" minOccurs="0"/&gt;
 *         &lt;element name="accountingPeriodMOSS" type="{http://www.stormware.cz/schema/version_2/type.xsd}string7" minOccurs="0"/&gt;
 *         &lt;element name="dateTaxOriginalDocumentMOSS" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="correctionMOSS" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *         &lt;element name="carrier" type="{http://www.stormware.cz/schema/version_2/type.xsd}carrierType" minOccurs="0"/&gt;
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="intNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="liquidation" type="{http://www.stormware.cz/schema/version_2/type.xsd}liquidationType" minOccurs="0"/&gt;
 *         &lt;element name="applied" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="histRate" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *         &lt;element name="markRecord" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *         &lt;element name="labels" type="{http://www.stormware.cz/schema/version_2/type.xsd}labelsType" minOccurs="0"/&gt;
 *         &lt;element name="intrastat" type="{http://www.stormware.cz/schema/version_2/invoice.xsd}intrastatType" minOccurs="0"/&gt;
 *         &lt;element name="parameters" type="{http://www.stormware.cz/schema/version_2/type.xsd}parametersType" minOccurs="0"/&gt;
 *         &lt;element name="validate" type="{http://www.stormware.cz/schema/version_2/type.xsd}typeValidate" minOccurs="0"/&gt;
 *         &lt;element name="postponedIssue" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceHeaderType", propOrder = {

})
public class InvoiceHeaderType {

    protected BigInteger id;
    protected ExtIdType extId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected InvoiceTypeType invoiceType;
    @XmlSchemaType(name = "string")
    protected StornoType storno;
    @XmlElement(defaultValue = "business")
    @XmlSchemaType(name = "string")
    protected SphereTypeType sphereType;
    protected NumberType number;
    protected String symVar;
    protected String originalDocument;
    protected String originalDocumentNumber;
    protected String symPar;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateTax;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateAccounting;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateKHDPH;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDue;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateApplicationVAT;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDelivery;
    protected AccountingType accounting;
    protected ClassificationVATType classificationVAT;
    protected RefType classificationKVDPH;
    protected String numberKHDPH;
    protected String numberKVDPH;
    protected String text;
    protected Address partnerIdentity;
    protected MyAddress myIdentity;
    protected RefType order;
    protected String numberOrder;
    protected String dateOrder;
    protected RefType priceLevel;
    protected PaymentType paymentType;
    protected AccountType account;
    protected String symConst;
    protected String symSpec;
    protected InvoiceHeaderType.PaymentAccount paymentAccount;
    protected String messageForRecipient;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfPaymentOrder;
    @XmlElement(defaultValue = "false")
    @XmlSchemaType(name = "string")
    protected Boolean paymentTerminal;
    protected RefType centre;
    protected RefType activity;
    protected RefType contract;
    protected RefTypeRegVATinEU regVATinEU;
    @XmlElement(name = "MOSS")
    protected MOSStype moss;
    protected ResourcesMOSStype evidentiaryResourcesMOSS;
    protected String accountingPeriodMOSS;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateTaxOriginalDocumentMOSS;
    @XmlElement(defaultValue = "false")
    @XmlSchemaType(name = "string")
    protected Boolean correctionMOSS;
    @XmlElementRef(name = "carrier", namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<CarrierType> carrier;
    protected String note;
    protected String intNote;
    protected LiquidationType liquidation;
    protected Double applied;
    @XmlElement(defaultValue = "false")
    @XmlSchemaType(name = "string")
    protected Boolean histRate;
    @XmlElement(defaultValue = "true")
    @XmlSchemaType(name = "string")
    protected Boolean markRecord;
    protected LabelsType labels;
    protected IntrastatType intrastat;
    protected ParametersType parameters;
    protected TypeValidate validate;
    @XmlElement(defaultValue = "false")
    @XmlSchemaType(name = "string")
    protected Boolean postponedIssue;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the extId property.
     * 
     * @return
     *     possible object is
     *     {@link ExtIdType }
     *     
     */
    public ExtIdType getExtId() {
        return extId;
    }

    /**
     * Sets the value of the extId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtIdType }
     *     
     */
    public void setExtId(ExtIdType value) {
        this.extId = value;
    }

    /**
     * Gets the value of the invoiceType property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTypeType }
     *     
     */
    public InvoiceTypeType getInvoiceType() {
        return invoiceType;
    }

    /**
     * Sets the value of the invoiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTypeType }
     *     
     */
    public void setInvoiceType(InvoiceTypeType value) {
        this.invoiceType = value;
    }

    /**
     * Gets the value of the storno property.
     * 
     * @return
     *     possible object is
     *     {@link StornoType }
     *     
     */
    public StornoType getStorno() {
        return storno;
    }

    /**
     * Sets the value of the storno property.
     * 
     * @param value
     *     allowed object is
     *     {@link StornoType }
     *     
     */
    public void setStorno(StornoType value) {
        this.storno = value;
    }

    /**
     * Gets the value of the sphereType property.
     * 
     * @return
     *     possible object is
     *     {@link SphereTypeType }
     *     
     */
    public SphereTypeType getSphereType() {
        return sphereType;
    }

    /**
     * Sets the value of the sphereType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SphereTypeType }
     *     
     */
    public void setSphereType(SphereTypeType value) {
        this.sphereType = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumber(NumberType value) {
        this.number = value;
    }

    /**
     * Gets the value of the symVar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymVar() {
        return symVar;
    }

    /**
     * Sets the value of the symVar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymVar(String value) {
        this.symVar = value;
    }

    /**
     * Gets the value of the originalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDocument() {
        return originalDocument;
    }

    /**
     * Sets the value of the originalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDocument(String value) {
        this.originalDocument = value;
    }

    /**
     * Gets the value of the originalDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDocumentNumber() {
        return originalDocumentNumber;
    }

    /**
     * Sets the value of the originalDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDocumentNumber(String value) {
        this.originalDocumentNumber = value;
    }

    /**
     * Gets the value of the symPar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymPar() {
        return symPar;
    }

    /**
     * Sets the value of the symPar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymPar(String value) {
        this.symPar = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the dateTax property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTax() {
        return dateTax;
    }

    /**
     * Sets the value of the dateTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTax(XMLGregorianCalendar value) {
        this.dateTax = value;
    }

    /**
     * Gets the value of the dateAccounting property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAccounting() {
        return dateAccounting;
    }

    /**
     * Sets the value of the dateAccounting property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAccounting(XMLGregorianCalendar value) {
        this.dateAccounting = value;
    }

    /**
     * Gets the value of the dateKHDPH property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateKHDPH() {
        return dateKHDPH;
    }

    /**
     * Sets the value of the dateKHDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateKHDPH(XMLGregorianCalendar value) {
        this.dateKHDPH = value;
    }

    /**
     * Gets the value of the dateDue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDue() {
        return dateDue;
    }

    /**
     * Sets the value of the dateDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDue(XMLGregorianCalendar value) {
        this.dateDue = value;
    }

    /**
     * Gets the value of the dateApplicationVAT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateApplicationVAT() {
        return dateApplicationVAT;
    }

    /**
     * Sets the value of the dateApplicationVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateApplicationVAT(XMLGregorianCalendar value) {
        this.dateApplicationVAT = value;
    }

    /**
     * Gets the value of the dateDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDelivery() {
        return dateDelivery;
    }

    /**
     * Sets the value of the dateDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDelivery(XMLGregorianCalendar value) {
        this.dateDelivery = value;
    }

    /**
     * Gets the value of the accounting property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingType }
     *     
     */
    public AccountingType getAccounting() {
        return accounting;
    }

    /**
     * Sets the value of the accounting property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingType }
     *     
     */
    public void setAccounting(AccountingType value) {
        this.accounting = value;
    }

    /**
     * Gets the value of the classificationVAT property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationVATType }
     *     
     */
    public ClassificationVATType getClassificationVAT() {
        return classificationVAT;
    }

    /**
     * Sets the value of the classificationVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationVATType }
     *     
     */
    public void setClassificationVAT(ClassificationVATType value) {
        this.classificationVAT = value;
    }

    /**
     * Gets the value of the classificationKVDPH property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getClassificationKVDPH() {
        return classificationKVDPH;
    }

    /**
     * Sets the value of the classificationKVDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setClassificationKVDPH(RefType value) {
        this.classificationKVDPH = value;
    }

    /**
     * Gets the value of the numberKHDPH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberKHDPH() {
        return numberKHDPH;
    }

    /**
     * Sets the value of the numberKHDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberKHDPH(String value) {
        this.numberKHDPH = value;
    }

    /**
     * Gets the value of the numberKVDPH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberKVDPH() {
        return numberKVDPH;
    }

    /**
     * Sets the value of the numberKVDPH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberKVDPH(String value) {
        this.numberKVDPH = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the partnerIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getPartnerIdentity() {
        return partnerIdentity;
    }

    /**
     * Sets the value of the partnerIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setPartnerIdentity(Address value) {
        this.partnerIdentity = value;
    }

    /**
     * Gets the value of the myIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link MyAddress }
     *     
     */
    public MyAddress getMyIdentity() {
        return myIdentity;
    }

    /**
     * Sets the value of the myIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MyAddress }
     *     
     */
    public void setMyIdentity(MyAddress value) {
        this.myIdentity = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setOrder(RefType value) {
        this.order = value;
    }

    /**
     * Gets the value of the numberOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOrder() {
        return numberOrder;
    }

    /**
     * Sets the value of the numberOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOrder(String value) {
        this.numberOrder = value;
    }

    /**
     * Gets the value of the dateOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOrder() {
        return dateOrder;
    }

    /**
     * Sets the value of the dateOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOrder(String value) {
        this.dateOrder = value;
    }

    /**
     * Gets the value of the priceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getPriceLevel() {
        return priceLevel;
    }

    /**
     * Sets the value of the priceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setPriceLevel(RefType value) {
        this.priceLevel = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setPaymentType(PaymentType value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setAccount(AccountType value) {
        this.account = value;
    }

    /**
     * Gets the value of the symConst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymConst() {
        return symConst;
    }

    /**
     * Sets the value of the symConst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymConst(String value) {
        this.symConst = value;
    }

    /**
     * Gets the value of the symSpec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymSpec() {
        return symSpec;
    }

    /**
     * Sets the value of the symSpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymSpec(String value) {
        this.symSpec = value;
    }

    /**
     * Gets the value of the paymentAccount property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceHeaderType.PaymentAccount }
     *     
     */
    public InvoiceHeaderType.PaymentAccount getPaymentAccount() {
        return paymentAccount;
    }

    /**
     * Sets the value of the paymentAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceHeaderType.PaymentAccount }
     *     
     */
    public void setPaymentAccount(InvoiceHeaderType.PaymentAccount value) {
        this.paymentAccount = value;
    }

    /**
     * Gets the value of the messageForRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageForRecipient() {
        return messageForRecipient;
    }

    /**
     * Sets the value of the messageForRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageForRecipient(String value) {
        this.messageForRecipient = value;
    }

    /**
     * Gets the value of the dateOfPaymentOrder property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfPaymentOrder() {
        return dateOfPaymentOrder;
    }

    /**
     * Sets the value of the dateOfPaymentOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfPaymentOrder(XMLGregorianCalendar value) {
        this.dateOfPaymentOrder = value;
    }

    /**
     * Gets the value of the paymentTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPaymentTerminal() {
        return paymentTerminal;
    }

    /**
     * Sets the value of the paymentTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaymentTerminal(Boolean value) {
        this.paymentTerminal = value;
    }

    /**
     * Gets the value of the centre property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getCentre() {
        return centre;
    }

    /**
     * Sets the value of the centre property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setCentre(RefType value) {
        this.centre = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setActivity(RefType value) {
        this.activity = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setContract(RefType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the regVATinEU property.
     * 
     * @return
     *     possible object is
     *     {@link RefTypeRegVATinEU }
     *     
     */
    public RefTypeRegVATinEU getRegVATinEU() {
        return regVATinEU;
    }

    /**
     * Sets the value of the regVATinEU property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTypeRegVATinEU }
     *     
     */
    public void setRegVATinEU(RefTypeRegVATinEU value) {
        this.regVATinEU = value;
    }

    /**
     * Gets the value of the moss property.
     * 
     * @return
     *     possible object is
     *     {@link MOSStype }
     *     
     */
    public MOSStype getMOSS() {
        return moss;
    }

    /**
     * Sets the value of the moss property.
     * 
     * @param value
     *     allowed object is
     *     {@link MOSStype }
     *     
     */
    public void setMOSS(MOSStype value) {
        this.moss = value;
    }

    /**
     * Gets the value of the evidentiaryResourcesMOSS property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcesMOSStype }
     *     
     */
    public ResourcesMOSStype getEvidentiaryResourcesMOSS() {
        return evidentiaryResourcesMOSS;
    }

    /**
     * Sets the value of the evidentiaryResourcesMOSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcesMOSStype }
     *     
     */
    public void setEvidentiaryResourcesMOSS(ResourcesMOSStype value) {
        this.evidentiaryResourcesMOSS = value;
    }

    /**
     * Gets the value of the accountingPeriodMOSS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingPeriodMOSS() {
        return accountingPeriodMOSS;
    }

    /**
     * Sets the value of the accountingPeriodMOSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingPeriodMOSS(String value) {
        this.accountingPeriodMOSS = value;
    }

    /**
     * Gets the value of the dateTaxOriginalDocumentMOSS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTaxOriginalDocumentMOSS() {
        return dateTaxOriginalDocumentMOSS;
    }

    /**
     * Sets the value of the dateTaxOriginalDocumentMOSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTaxOriginalDocumentMOSS(XMLGregorianCalendar value) {
        this.dateTaxOriginalDocumentMOSS = value;
    }

    /**
     * Gets the value of the correctionMOSS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCorrectionMOSS() {
        return correctionMOSS;
    }

    /**
     * Sets the value of the correctionMOSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCorrectionMOSS(Boolean value) {
        this.correctionMOSS = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CarrierType }{@code >}
     *     
     */
    public JAXBElement<CarrierType> getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CarrierType }{@code >}
     *     
     */
    public void setCarrier(JAXBElement<CarrierType> value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the intNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntNote() {
        return intNote;
    }

    /**
     * Sets the value of the intNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntNote(String value) {
        this.intNote = value;
    }

    /**
     * Gets the value of the liquidation property.
     * 
     * @return
     *     possible object is
     *     {@link LiquidationType }
     *     
     */
    public LiquidationType getLiquidation() {
        return liquidation;
    }

    /**
     * Sets the value of the liquidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiquidationType }
     *     
     */
    public void setLiquidation(LiquidationType value) {
        this.liquidation = value;
    }

    /**
     * Gets the value of the applied property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getApplied() {
        return applied;
    }

    /**
     * Sets the value of the applied property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setApplied(Double value) {
        this.applied = value;
    }

    /**
     * Gets the value of the histRate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getHistRate() {
        return histRate;
    }

    /**
     * Sets the value of the histRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHistRate(Boolean value) {
        this.histRate = value;
    }

    /**
     * Gets the value of the markRecord property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMarkRecord() {
        return markRecord;
    }

    /**
     * Sets the value of the markRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMarkRecord(Boolean value) {
        this.markRecord = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link LabelsType }
     *     
     */
    public LabelsType getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelsType }
     *     
     */
    public void setLabels(LabelsType value) {
        this.labels = value;
    }

    /**
     * Gets the value of the intrastat property.
     * 
     * @return
     *     possible object is
     *     {@link IntrastatType }
     *     
     */
    public IntrastatType getIntrastat() {
        return intrastat;
    }

    /**
     * Sets the value of the intrastat property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntrastatType }
     *     
     */
    public void setIntrastat(IntrastatType value) {
        this.intrastat = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersType }
     *     
     */
    public ParametersType getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersType }
     *     
     */
    public void setParameters(ParametersType value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the validate property.
     * 
     * @return
     *     possible object is
     *     {@link TypeValidate }
     *     
     */
    public TypeValidate getValidate() {
        return validate;
    }

    /**
     * Sets the value of the validate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeValidate }
     *     
     */
    public void setValidate(TypeValidate value) {
        this.validate = value;
    }

    /**
     * Gets the value of the postponedIssue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPostponedIssue() {
        return postponedIssue;
    }

    /**
     * Sets the value of the postponedIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPostponedIssue(Boolean value) {
        this.postponedIssue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;group ref="{http://www.stormware.cz/schema/version_2/type.xsd}myGroupOfAccount"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNo",
        "bankCode"
    })
    public static class PaymentAccount {

        @XmlElement(namespace = "http://www.stormware.cz/schema/version_2/type.xsd", required = true)
        protected String accountNo;
        @XmlElement(namespace = "http://www.stormware.cz/schema/version_2/type.xsd", required = true)
        protected String bankCode;

        /**
         * Gets the value of the accountNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNo() {
            return accountNo;
        }

        /**
         * Sets the value of the accountNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountNo(String value) {
            this.accountNo = value;
        }

        /**
         * Gets the value of the bankCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankCode() {
            return bankCode;
        }

        /**
         * Sets the value of the bankCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankCode(String value) {
            this.bankCode = value;
        }

    }

}
