//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.invoice;

import javax.xml.namespace.QName;
import cz.stormware.schema.version_2.type.CarrierType;
import cz.stormware.schema.version_2.type.RoundingItemType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.version_2.invoice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Invoice_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "invoice");
    private final static QName _InvoiceResponse_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "invoiceResponse");
    private final static QName _InvoiceDetailTypeInvoiceItem_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "invoiceItem");
    private final static QName _InvoiceDetailTypeInvoiceAdvancePaymentItem_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "invoiceAdvancePaymentItem");
    private final static QName _InvoiceDetailTypeRoundingItem_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "roundingItem");
    private final static QName _InvoiceHeaderTypeCarrier_QNAME = new QName("http://www.stormware.cz/schema/version_2/invoice.xsd", "carrier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.version_2.invoice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceHeaderType }
     * 
     */
    public InvoiceHeaderType createInvoiceHeaderType() {
        return new InvoiceHeaderType();
    }

    /**
     * Create an instance of {@link InvoiceType }
     * 
     */
    public InvoiceType createInvoiceType() {
        return new InvoiceType();
    }

    /**
     * Create an instance of {@link InvoiceResponseType }
     * 
     */
    public InvoiceResponseType createInvoiceResponseType() {
        return new InvoiceResponseType();
    }

    /**
     * Create an instance of {@link InvoiceRetentionsType }
     * 
     */
    public InvoiceRetentionsType createInvoiceRetentionsType() {
        return new InvoiceRetentionsType();
    }

    /**
     * Create an instance of {@link InvoiceDetailType }
     * 
     */
    public InvoiceDetailType createInvoiceDetailType() {
        return new InvoiceDetailType();
    }

    /**
     * Create an instance of {@link InvoiceSummaryType }
     * 
     */
    public InvoiceSummaryType createInvoiceSummaryType() {
        return new InvoiceSummaryType();
    }

    /**
     * Create an instance of {@link InvoiceItemType }
     * 
     */
    public InvoiceItemType createInvoiceItemType() {
        return new InvoiceItemType();
    }

    /**
     * Create an instance of {@link InvoiceAdvancePaymentItemType }
     * 
     */
    public InvoiceAdvancePaymentItemType createInvoiceAdvancePaymentItemType() {
        return new InvoiceAdvancePaymentItemType();
    }

    /**
     * Create an instance of {@link IntrastatType }
     * 
     */
    public IntrastatType createIntrastatType() {
        return new IntrastatType();
    }

    /**
     * Create an instance of {@link IntrastatItemType }
     * 
     */
    public IntrastatItemType createIntrastatItemType() {
        return new IntrastatItemType();
    }

    /**
     * Create an instance of {@link InvoiceRetentionType }
     * 
     */
    public InvoiceRetentionType createInvoiceRetentionType() {
        return new InvoiceRetentionType();
    }

    /**
     * Create an instance of {@link InvoiceHeaderType.PaymentAccount }
     * 
     */
    public InvoiceHeaderType.PaymentAccount createInvoiceHeaderTypePaymentAccount() {
        return new InvoiceHeaderType.PaymentAccount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvoiceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "invoice")
    public JAXBElement<InvoiceType> createInvoice(InvoiceType value) {
        return new JAXBElement<InvoiceType>(_Invoice_QNAME, InvoiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvoiceResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "invoiceResponse")
    public JAXBElement<InvoiceResponseType> createInvoiceResponse(InvoiceResponseType value) {
        return new JAXBElement<InvoiceResponseType>(_InvoiceResponse_QNAME, InvoiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceItemType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvoiceItemType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "invoiceItem", scope = InvoiceDetailType.class)
    public JAXBElement<InvoiceItemType> createInvoiceDetailTypeInvoiceItem(InvoiceItemType value) {
        return new JAXBElement<InvoiceItemType>(_InvoiceDetailTypeInvoiceItem_QNAME, InvoiceItemType.class, InvoiceDetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceAdvancePaymentItemType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InvoiceAdvancePaymentItemType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "invoiceAdvancePaymentItem", scope = InvoiceDetailType.class)
    public JAXBElement<InvoiceAdvancePaymentItemType> createInvoiceDetailTypeInvoiceAdvancePaymentItem(InvoiceAdvancePaymentItemType value) {
        return new JAXBElement<InvoiceAdvancePaymentItemType>(_InvoiceDetailTypeInvoiceAdvancePaymentItem_QNAME, InvoiceAdvancePaymentItemType.class, InvoiceDetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoundingItemType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RoundingItemType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "roundingItem", scope = InvoiceDetailType.class)
    public JAXBElement<RoundingItemType> createInvoiceDetailTypeRoundingItem(RoundingItemType value) {
        return new JAXBElement<RoundingItemType>(_InvoiceDetailTypeRoundingItem_QNAME, RoundingItemType.class, InvoiceDetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarrierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CarrierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/invoice.xsd", name = "carrier", scope = InvoiceHeaderType.class)
    public JAXBElement<CarrierType> createInvoiceHeaderTypeCarrier(CarrierType value) {
        return new JAXBElement<CarrierType>(_InvoiceHeaderTypeCarrier_QNAME, CarrierType.class, InvoiceHeaderType.class, value);
    }

}
