//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.data;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.version_2.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataPack_QNAME = new QName("http://www.stormware.cz/schema/version_2/data.xsd", "dataPack");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.version_2.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataPackType }
     * 
     */
    public DataPackType createDataPackType() {
        return new DataPackType();
    }

    /**
     * Create an instance of {@link TransformationType }
     * 
     */
    public TransformationType createTransformationType() {
        return new TransformationType();
    }

    /**
     * Create an instance of {@link DataPackItemType }
     * 
     */
    public DataPackItemType createDataPackItemType() {
        return new DataPackItemType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataPackType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataPackType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/data.xsd", name = "dataPack")
    public JAXBElement<DataPackType> createDataPack(DataPackType value) {
        return new JAXBElement<DataPackType>(_DataPack_QNAME, DataPackType.class, null, value);
    }

}
