package cz.bbn.cerberus.approvement.enums;

public enum BusinessTripPurpose {

    VISITING_CUSTOMERS_AND_SUPPLIERS,
    MEETING_AT_OTHER_COMPANY_LOCATIONS,
    PROFESSIONAL_DEVELOPMENT_AND_ATTENDING_A_CONGRESS,
    MARKET_OR_PROMOTE_A_NEW_OR_EXISTING_PRODUCT,
    NETWORKING_BUILDING_NEW_PARTNERSHIP,
    STRENGHTENING_RELATIONSHIPS_WITH_CUSTOMERS,
    VISITING_PROJECT_SITE_FOR_EVALUATION,
    IDENTIFYING_TRENDS_AND_NEW_MARKETS,
    STRENGTHENING_EMPLOYEES_LOYALTY_TO_THE_BUSINESS
}
