//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.documentresponse;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="actionTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="add"/&gt;
 *     &lt;enumeration value="update"/&gt;
 *     &lt;enumeration value="delete"/&gt;
 *     &lt;enumeration value="print"/&gt;
 *     &lt;enumeration value="link"/&gt;
 *     &lt;enumeration value="sendEET"/&gt;
 *     &lt;enumeration value="accountingSalesVouchers"/&gt;
 *     &lt;enumeration value="isdoc"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "actionTypeEnum")
@XmlEnum
public enum ActionTypeEnum {

    @XmlEnumValue("add")
    ADD("add"),
    @XmlEnumValue("update")
    UPDATE("update"),
    @XmlEnumValue("delete")
    DELETE("delete"),
    @XmlEnumValue("print")
    PRINT("print"),
    @XmlEnumValue("link")
    LINK("link"),
    @XmlEnumValue("sendEET")
    SEND_EET("sendEET"),
    @XmlEnumValue("accountingSalesVouchers")
    ACCOUNTING_SALES_VOUCHERS("accountingSalesVouchers"),
    @XmlEnumValue("isdoc")
    ISDOC("isdoc");
    private final String value;

    ActionTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionTypeEnum fromValue(String v) {
        for (ActionTypeEnum c: ActionTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
