//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.documentresponse;

import cz.stormware.schema.version_2.invoice.InvoiceResponseType;
import cz.stormware.schema.version_2.print.PrintResponseType;
import cz.stormware.schema.version_2.type.StavType2;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="importDetails" type="{http://www.stormware.cz/schema/version_2/documentresponse.xsd}importDetailsType" minOccurs="0"/&gt;
 *         &lt;element name="producedDetails" type="{http://www.stormware.cz/schema/version_2/documentresponse.xsd}producedDetailsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="state" use="required" type="{http://www.stormware.cz/schema/version_2/type.xsd}stavType2" /&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentResponseType", propOrder = {
    "importDetails",
    "producedDetails"
})
@XmlSeeAlso({
    InvoiceResponseType.class,
    PrintResponseType.class
})
public class DocumentResponseType {

    protected ImportDetailsType importDetails;
    protected ProducedDetailsType producedDetails;
    @XmlAttribute(name = "state", required = true)
    protected StavType2 state;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the importDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ImportDetailsType }
     *     
     */
    public ImportDetailsType getImportDetails() {
        return importDetails;
    }

    /**
     * Sets the value of the importDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportDetailsType }
     *     
     */
    public void setImportDetails(ImportDetailsType value) {
        this.importDetails = value;
    }

    /**
     * Gets the value of the producedDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProducedDetailsType }
     *     
     */
    public ProducedDetailsType getProducedDetails() {
        return producedDetails;
    }

    /**
     * Sets the value of the producedDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducedDetailsType }
     *     
     */
    public void setProducedDetails(ProducedDetailsType value) {
        this.producedDetails = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StavType2 }
     *     
     */
    public StavType2 getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavType2 }
     *     
     */
    public void setState(StavType2 value) {
        this.state = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
