//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.documentresponse;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.version_2.documentresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.version_2.documentresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link DocumentResponseType }
     * 
     */
    public DocumentResponseType createDocumentResponseType() {
        return new DocumentResponseType();
    }

    /**
     * Create an instance of {@link ProducedDetailsType }
     * 
     */
    public ProducedDetailsType createProducedDetailsType() {
        return new ProducedDetailsType();
    }

    /**
     * Create an instance of {@link ImportDetailsType }
     * 
     */
    public ImportDetailsType createImportDetailsType() {
        return new ImportDetailsType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link ItemDetailsType }
     * 
     */
    public ItemDetailsType createItemDetailsType() {
        return new ItemDetailsType();
    }

    /**
     * Create an instance of {@link ListVersionType }
     * 
     */
    public ListVersionType createListVersionType() {
        return new ListVersionType();
    }

    /**
     * Create an instance of {@link PartsType }
     * 
     */
    public PartsType createPartsType() {
        return new PartsType();
    }

    /**
     * Create an instance of {@link ItemType.ProducedItem }
     * 
     */
    public ItemType.ProducedItem createItemTypeProducedItem() {
        return new ItemType.ProducedItem();
    }

}
