//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.print;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.version_2.print package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Print_QNAME = new QName("http://www.stormware.cz/schema/version_2/print.xsd", "print");
    private final static QName _PrintResponse_QNAME = new QName("http://www.stormware.cz/schema/version_2/print.xsd", "printResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.version_2.print
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrintType }
     * 
     */
    public PrintType createPrintType() {
        return new PrintType();
    }

    /**
     * Create an instance of {@link PrintResponseType }
     * 
     */
    public PrintResponseType createPrintResponseType() {
        return new PrintResponseType();
    }

    /**
     * Create an instance of {@link AgendaPrintType }
     * 
     */
    public AgendaPrintType createAgendaPrintType() {
        return new AgendaPrintType();
    }

    /**
     * Create an instance of {@link PrinterSettingsType }
     * 
     */
    public PrinterSettingsType createPrinterSettingsType() {
        return new PrinterSettingsType();
    }

    /**
     * Create an instance of {@link PDFType }
     * 
     */
    public PDFType createPDFType() {
        return new PDFType();
    }

    /**
     * Create an instance of {@link IsdocType }
     * 
     */
    public IsdocType createIsdocType() {
        return new IsdocType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link CheckboxType }
     * 
     */
    public CheckboxType createCheckboxType() {
        return new CheckboxType();
    }

    /**
     * Create an instance of {@link RadioButtonType }
     * 
     */
    public RadioButtonType createRadioButtonType() {
        return new RadioButtonType();
    }

    /**
     * Create an instance of {@link NumberType }
     * 
     */
    public NumberType createNumberType() {
        return new NumberType();
    }

    /**
     * Create an instance of {@link ComboboxType }
     * 
     */
    public ComboboxType createComboboxType() {
        return new ComboboxType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrintType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/print.xsd", name = "print")
    public JAXBElement<PrintType> createPrint(PrintType value) {
        return new JAXBElement<PrintType>(_Print_QNAME, PrintType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PrintResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.stormware.cz/schema/version_2/print.xsd", name = "printResponse")
    public JAXBElement<PrintResponseType> createPrintResponse(PrintResponseType value) {
        return new JAXBElement<PrintResponseType>(_PrintResponse_QNAME, PrintResponseType.class, null, value);
    }

}
