//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:43 PM CEST 
//


package cz.stormware.schema.version_2.print;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parametersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="copy" type="{http://www.stormware.cz/schema/version_2/print.xsd}copyType" minOccurs="0"/&gt;
 *         &lt;element name="datePrint" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="checkbox1" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="checkbox2" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="checkbox3" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="checkbox4" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="checkbox5" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="checkbox6" type="{http://www.stormware.cz/schema/version_2/print.xsd}checkboxType" minOccurs="0"/&gt;
 *         &lt;element name="radioButton1" type="{http://www.stormware.cz/schema/version_2/print.xsd}radioButtonType" minOccurs="0"/&gt;
 *         &lt;element name="spin1" type="{http://www.stormware.cz/schema/version_2/print.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="currency1" type="{http://www.stormware.cz/schema/version_2/print.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="month1" type="{http://www.stormware.cz/schema/version_2/print.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="month2" type="{http://www.stormware.cz/schema/version_2/print.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="year1" type="{http://www.stormware.cz/schema/version_2/print.xsd}numberType" minOccurs="0"/&gt;
 *         &lt;element name="date1" type="{http://www.stormware.cz/schema/version_2/print.xsd}dateType" minOccurs="0"/&gt;
 *         &lt;element name="date2" type="{http://www.stormware.cz/schema/version_2/print.xsd}dateType" minOccurs="0"/&gt;
 *         &lt;element name="date3" type="{http://www.stormware.cz/schema/version_2/print.xsd}dateType" minOccurs="0"/&gt;
 *         &lt;element name="date4" type="{http://www.stormware.cz/schema/version_2/print.xsd}dateType" minOccurs="0"/&gt;
 *         &lt;element name="text1" type="{http://www.stormware.cz/schema/version_2/print.xsd}textType" minOccurs="0"/&gt;
 *         &lt;element name="text2" type="{http://www.stormware.cz/schema/version_2/print.xsd}textType" minOccurs="0"/&gt;
 *         &lt;element name="text3" type="{http://www.stormware.cz/schema/version_2/print.xsd}textType" minOccurs="0"/&gt;
 *         &lt;element name="combobox1" type="{http://www.stormware.cz/schema/version_2/print.xsd}comboboxType" minOccurs="0"/&gt;
 *         &lt;element name="combobox2" type="{http://www.stormware.cz/schema/version_2/print.xsd}comboboxType" minOccurs="0"/&gt;
 *         &lt;element name="combobox3" type="{http://www.stormware.cz/schema/version_2/print.xsd}comboboxType" minOccurs="0"/&gt;
 *         &lt;element name="comboboxEx1" type="{http://www.stormware.cz/schema/version_2/print.xsd}comboboxType" minOccurs="0"/&gt;
 *         &lt;element name="comboboxEx2" type="{http://www.stormware.cz/schema/version_2/print.xsd}comboboxType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parametersType", propOrder = {

})
public class ParametersType {

    @XmlElement(defaultValue = "1")
    protected BigDecimal copy;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePrint;
    protected CheckboxType checkbox1;
    protected CheckboxType checkbox2;
    protected CheckboxType checkbox3;
    protected CheckboxType checkbox4;
    protected CheckboxType checkbox5;
    protected CheckboxType checkbox6;
    protected RadioButtonType radioButton1;
    protected NumberType spin1;
    protected NumberType currency1;
    protected NumberType month1;
    protected NumberType month2;
    protected NumberType year1;
    protected DateType date1;
    protected DateType date2;
    protected DateType date3;
    protected DateType date4;
    protected TextType text1;
    protected TextType text2;
    protected TextType text3;
    protected ComboboxType combobox1;
    protected ComboboxType combobox2;
    protected ComboboxType combobox3;
    protected ComboboxType comboboxEx1;
    protected ComboboxType comboboxEx2;

    /**
     * Gets the value of the copy property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCopy() {
        return copy;
    }

    /**
     * Sets the value of the copy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCopy(BigDecimal value) {
        this.copy = value;
    }

    /**
     * Gets the value of the datePrint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePrint() {
        return datePrint;
    }

    /**
     * Sets the value of the datePrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePrint(XMLGregorianCalendar value) {
        this.datePrint = value;
    }

    /**
     * Gets the value of the checkbox1 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox1() {
        return checkbox1;
    }

    /**
     * Sets the value of the checkbox1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox1(CheckboxType value) {
        this.checkbox1 = value;
    }

    /**
     * Gets the value of the checkbox2 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox2() {
        return checkbox2;
    }

    /**
     * Sets the value of the checkbox2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox2(CheckboxType value) {
        this.checkbox2 = value;
    }

    /**
     * Gets the value of the checkbox3 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox3() {
        return checkbox3;
    }

    /**
     * Sets the value of the checkbox3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox3(CheckboxType value) {
        this.checkbox3 = value;
    }

    /**
     * Gets the value of the checkbox4 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox4() {
        return checkbox4;
    }

    /**
     * Sets the value of the checkbox4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox4(CheckboxType value) {
        this.checkbox4 = value;
    }

    /**
     * Gets the value of the checkbox5 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox5() {
        return checkbox5;
    }

    /**
     * Sets the value of the checkbox5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox5(CheckboxType value) {
        this.checkbox5 = value;
    }

    /**
     * Gets the value of the checkbox6 property.
     * 
     * @return
     *     possible object is
     *     {@link CheckboxType }
     *     
     */
    public CheckboxType getCheckbox6() {
        return checkbox6;
    }

    /**
     * Sets the value of the checkbox6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckboxType }
     *     
     */
    public void setCheckbox6(CheckboxType value) {
        this.checkbox6 = value;
    }

    /**
     * Gets the value of the radioButton1 property.
     * 
     * @return
     *     possible object is
     *     {@link RadioButtonType }
     *     
     */
    public RadioButtonType getRadioButton1() {
        return radioButton1;
    }

    /**
     * Sets the value of the radioButton1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioButtonType }
     *     
     */
    public void setRadioButton1(RadioButtonType value) {
        this.radioButton1 = value;
    }

    /**
     * Gets the value of the spin1 property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getSpin1() {
        return spin1;
    }

    /**
     * Sets the value of the spin1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setSpin1(NumberType value) {
        this.spin1 = value;
    }

    /**
     * Gets the value of the currency1 property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getCurrency1() {
        return currency1;
    }

    /**
     * Sets the value of the currency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setCurrency1(NumberType value) {
        this.currency1 = value;
    }

    /**
     * Gets the value of the month1 property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getMonth1() {
        return month1;
    }

    /**
     * Sets the value of the month1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setMonth1(NumberType value) {
        this.month1 = value;
    }

    /**
     * Gets the value of the month2 property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getMonth2() {
        return month2;
    }

    /**
     * Sets the value of the month2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setMonth2(NumberType value) {
        this.month2 = value;
    }

    /**
     * Gets the value of the year1 property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getYear1() {
        return year1;
    }

    /**
     * Sets the value of the year1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setYear1(NumberType value) {
        this.year1 = value;
    }

    /**
     * Gets the value of the date1 property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate1() {
        return date1;
    }

    /**
     * Sets the value of the date1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate1(DateType value) {
        this.date1 = value;
    }

    /**
     * Gets the value of the date2 property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate2() {
        return date2;
    }

    /**
     * Sets the value of the date2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate2(DateType value) {
        this.date2 = value;
    }

    /**
     * Gets the value of the date3 property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate3() {
        return date3;
    }

    /**
     * Sets the value of the date3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate3(DateType value) {
        this.date3 = value;
    }

    /**
     * Gets the value of the date4 property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate4() {
        return date4;
    }

    /**
     * Sets the value of the date4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate4(DateType value) {
        this.date4 = value;
    }

    /**
     * Gets the value of the text1 property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText1() {
        return text1;
    }

    /**
     * Sets the value of the text1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText1(TextType value) {
        this.text1 = value;
    }

    /**
     * Gets the value of the text2 property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText2() {
        return text2;
    }

    /**
     * Sets the value of the text2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText2(TextType value) {
        this.text2 = value;
    }

    /**
     * Gets the value of the text3 property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getText3() {
        return text3;
    }

    /**
     * Sets the value of the text3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setText3(TextType value) {
        this.text3 = value;
    }

    /**
     * Gets the value of the combobox1 property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getCombobox1() {
        return combobox1;
    }

    /**
     * Sets the value of the combobox1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setCombobox1(ComboboxType value) {
        this.combobox1 = value;
    }

    /**
     * Gets the value of the combobox2 property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getCombobox2() {
        return combobox2;
    }

    /**
     * Sets the value of the combobox2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setCombobox2(ComboboxType value) {
        this.combobox2 = value;
    }

    /**
     * Gets the value of the combobox3 property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getCombobox3() {
        return combobox3;
    }

    /**
     * Sets the value of the combobox3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setCombobox3(ComboboxType value) {
        this.combobox3 = value;
    }

    /**
     * Gets the value of the comboboxEx1 property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getComboboxEx1() {
        return comboboxEx1;
    }

    /**
     * Sets the value of the comboboxEx1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setComboboxEx1(ComboboxType value) {
        this.comboboxEx1 = value;
    }

    /**
     * Gets the value of the comboboxEx2 property.
     * 
     * @return
     *     possible object is
     *     {@link ComboboxType }
     *     
     */
    public ComboboxType getComboboxEx2() {
        return comboboxEx2;
    }

    /**
     * Sets the value of the comboboxEx2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComboboxType }
     *     
     */
    public void setComboboxEx2(ComboboxType value) {
        this.comboboxEx2 = value;
    }

}
