package cz.mfcr.adis.rozhranicrpdph;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-09-18T12:18:47.615+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/", name = "rozhraniCRPDPH")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RozhraniCRPDPH {

    /**
     * Vrátí seznam všech nespolehlivých plátců
     *       
     */
    @WebMethod(action = "http://adis.mfcr.cz/rozhraniCRPDPH/getSeznamNespolehlivyPlatce")
    @WebResult(name = "SeznamNespolehlivyPlatceResponse", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/", partName = "parameters")
    public SeznamNespolehlivyPlatceResponse getSeznamNespolehlivyPlatce(

        @WebParam(partName = "parameters", name = "SeznamNespolehlivyPlatceRequest", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/")
        SeznamNespolehlivyPlatceRequest parameters
    );

    /**
     * Pro zadaná DIČ vratí informace o
     *         nespolehlivosti plátce DPH a seznam jeho zveřejněných účtů.
     *       
     */
    @WebMethod(action = "http://adis.mfcr.cz/rozhraniCRPDPH/getStatusNespolehlivyPlatce")
    @WebResult(name = "StatusNespolehlivyPlatceResponse", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/", partName = "parameters")
    public StatusNespolehlivyPlatceResponse getStatusNespolehlivyPlatce(

        @WebParam(partName = "parameters", name = "StatusNespolehlivyPlatceRequest", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/")
        StatusNespolehlivyPlatceRequest parameters
    );

    /**
     * Pro zadaná DIČ vratí informace o
     *         nespolehlivosti plátce DPH a seznam jeho zveřejněných účtů. 
     *         Ke každému plácti vrátí navíc název a adresu subjektu.
     *       
     */
    @WebMethod(action = "http://adis.mfcr.cz/rozhraniCRPDPH/getStatusNespolehlivyPlatceRozsireny")
    @WebResult(name = "StatusNespolehlivyPlatceRozsirenyResponse", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/", partName = "parameters")
    public StatusNespolehlivyPlatceRozsirenyResponse getStatusNespolehlivyPlatceRozsireny(

        @WebParam(partName = "parameters", name = "StatusNespolehlivyPlatceRozsirenyRequest", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/")
        StatusNespolehlivyPlatceRequest parameters
    );

    /**
     * Pro zadaná DIČ vratí informace o
     *         nespolehlivosti plátce DPH/identifikované osobě a seznam jeho zveřejněných účtů. 
     *         Ke každému plácti/identifikované osobě vrátí navíc název a adresu subjektu.
     *       
     */
    @WebMethod(action = "http://adis.mfcr.cz/rozhraniCRPDPH/getStatusNespolehlivySubjektRozsireny")
    @WebResult(name = "StatusNespolehlivySubjektRozsirenyResponse", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/", partName = "parameters")
    public StatusNespolehlivySubjektRozsirenyResponse getStatusNespolehlivySubjektRozsireny(

        @WebParam(partName = "parameters", name = "StatusNespolehlivySubjektRozsirenyRequest", targetNamespace = "http://adis.mfcr.cz/rozhraniCRPDPH/")
        StatusNespolehlivyPlatceRequest parameters
    );
}
