package cz.bbn.cerberus.usermessage;

public enum MessageType {

    TEST_MESSAGE,
    SUBJECT_CHANGE,
    USER_TASK_IS_COMING,
    NEW_UNREAD_MAIL,
    CONTRACT_ENDING,
    INVOICE_PLANNED,
    NEW_OPPORTUNITY,
    NEW_PROJECT,
    NEW_INVOICE,
    SUPPLIER_LINKED,
    NEW_CONTRACT,
    NEW_OFFER,
    NEW_APPROVEMENT_REQUEST,
    APPROVEMENT_REQUEST_DENIED,
    APPROVEMENT_REQUEST_RETURNED,
    APPROVEMENT_REQUEST_APPROVED,
    MASTER_NEW_APPROVEMENT_REQUEST,
    MASTER_CHANGED_APPROVEMENT_REQUEST,
    TASK_STATE_CHANGE,
    TASK_ASSIGNEE_CHANGED,
    TASK_RESOLVED,
    TASK_UPDATED,
    TASK_CHECK_LIST_DATE,
}
