//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agendaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="agendaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="issuedInvoice"/&gt;
 *     &lt;enumeration value="issuedAdvanceInvoice"/&gt;
 *     &lt;enumeration value="receivable"/&gt;
 *     &lt;enumeration value="receivedInvoice"/&gt;
 *     &lt;enumeration value="receivedAdvanceInvoice"/&gt;
 *     &lt;enumeration value="commitment"/&gt;
 *     &lt;enumeration value="internalDocuments"/&gt;
 *     &lt;enumeration value="issuedOrder"/&gt;
 *     &lt;enumeration value="receivedOrder"/&gt;
 *     &lt;enumeration value="issuedOffer"/&gt;
 *     &lt;enumeration value="receivedOffer"/&gt;
 *     &lt;enumeration value="issuedEnquiry"/&gt;
 *     &lt;enumeration value="receivedEnquiry"/&gt;
 *     &lt;enumeration value="receiptVoucher"/&gt;
 *     &lt;enumeration value="issueSlip"/&gt;
 *     &lt;enumeration value="transfer"/&gt;
 *     &lt;enumeration value="production"/&gt;
 *     &lt;enumeration value="productRequirements"/&gt;
 *     &lt;enumeration value="claims"/&gt;
 *     &lt;enumeration value="claimsOld"/&gt;
 *     &lt;enumeration value="service"/&gt;
 *     &lt;enumeration value="fixedAssets"/&gt;
 *     &lt;enumeration value="lowValueAssets"/&gt;
 *     &lt;enumeration value="salesVouchers"/&gt;
 *     &lt;enumeration value="cashbox"/&gt;
 *     &lt;enumeration value="paymentOrders"/&gt;
 *     &lt;enumeration value="accrualsAndDeferrals"/&gt;
 *     &lt;enumeration value="correctiveItems"/&gt;
 *     &lt;enumeration value="shipments"/&gt;
 *     &lt;enumeration value="electronicRecordsOfSales"/&gt;
 *     &lt;enumeration value="registerOfCure"/&gt;
 *     &lt;enumeration value="domesticTravelOrder"/&gt;
 *     &lt;enumeration value="foreignTravelOrders"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "agendaType")
@XmlEnum
public enum AgendaType {


    /**
     * Vydaná faktura.
     * 
     */
    @XmlEnumValue("issuedInvoice")
    ISSUED_INVOICE("issuedInvoice"),

    /**
     * Vydaná zálohová faktura.
     * 
     */
    @XmlEnumValue("issuedAdvanceInvoice")
    ISSUED_ADVANCE_INVOICE("issuedAdvanceInvoice"),

    /**
     * Ostatní pohledávka.
     * 
     */
    @XmlEnumValue("receivable")
    RECEIVABLE("receivable"),

    /**
     * Přijatá faktura.
     * 
     */
    @XmlEnumValue("receivedInvoice")
    RECEIVED_INVOICE("receivedInvoice"),

    /**
     * Přijatá zálohová faktura.
     * 
     */
    @XmlEnumValue("receivedAdvanceInvoice")
    RECEIVED_ADVANCE_INVOICE("receivedAdvanceInvoice"),

    /**
     * Ostatní závazek.
     * 
     */
    @XmlEnumValue("commitment")
    COMMITMENT("commitment"),

    /**
     * Interní doklady.
     * 
     */
    @XmlEnumValue("internalDocuments")
    INTERNAL_DOCUMENTS("internalDocuments"),

    /**
     * Vydaná objednávka.
     * 
     */
    @XmlEnumValue("issuedOrder")
    ISSUED_ORDER("issuedOrder"),

    /**
     * Přijatá objednávka.
     * 
     */
    @XmlEnumValue("receivedOrder")
    RECEIVED_ORDER("receivedOrder"),

    /**
     * Vydaná nabídka.
     * 
     */
    @XmlEnumValue("issuedOffer")
    ISSUED_OFFER("issuedOffer"),

    /**
     * Přijatá nabídka.
     * 
     */
    @XmlEnumValue("receivedOffer")
    RECEIVED_OFFER("receivedOffer"),

    /**
     * Vydaná poptávka.
     * 
     */
    @XmlEnumValue("issuedEnquiry")
    ISSUED_ENQUIRY("issuedEnquiry"),

    /**
     * Přijatá poptávka.
     * 
     */
    @XmlEnumValue("receivedEnquiry")
    RECEIVED_ENQUIRY("receivedEnquiry"),

    /**
     * Příjemka.
     * 
     */
    @XmlEnumValue("receiptVoucher")
    RECEIPT_VOUCHER("receiptVoucher"),

    /**
     * Výdejka.
     * 
     */
    @XmlEnumValue("issueSlip")
    ISSUE_SLIP("issueSlip"),

    /**
     * Převodka.
     * 
     */
    @XmlEnumValue("transfer")
    TRANSFER("transfer"),

    /**
     * Výroba.
     * 
     */
    @XmlEnumValue("production")
    PRODUCTION("production"),

    /**
     * Výrobní požadavky.
     * 
     */
    @XmlEnumValue("productRequirements")
    PRODUCT_REQUIREMENTS("productRequirements"),

    /**
     * Reklamace.
     * 
     */
    @XmlEnumValue("claims")
    CLAIMS("claims"),

    /**
     * Reklamace (staré).
     * 
     */
    @XmlEnumValue("claimsOld")
    CLAIMS_OLD("claimsOld"),

    /**
     * Servis.
     * 
     */
    @XmlEnumValue("service")
    SERVICE("service"),

    /**
     * Majetek.
     * 
     */
    @XmlEnumValue("fixedAssets")
    FIXED_ASSETS("fixedAssets"),

    /**
     * Drobný majetek.
     * 
     */
    @XmlEnumValue("lowValueAssets")
    LOW_VALUE_ASSETS("lowValueAssets"),

    /**
     * Prodejky.
     * 
     */
    @XmlEnumValue("salesVouchers")
    SALES_VOUCHERS("salesVouchers"),

    /**
     * Pokladna.
     * 
     */
    @XmlEnumValue("cashbox")
    CASHBOX("cashbox"),

    /**
     * Bankovní příkazy.
     * 
     */
    @XmlEnumValue("paymentOrders")
    PAYMENT_ORDERS("paymentOrders"),

    /**
     * Časové rozlišení.
     * 
     */
    @XmlEnumValue("accrualsAndDeferrals")
    ACCRUALS_AND_DEFERRALS("accrualsAndDeferrals"),

    /**
     * Opravné položky.
     * 
     */
    @XmlEnumValue("correctiveItems")
    CORRECTIVE_ITEMS("correctiveItems"),

    /**
     * Zásilky.
     * 
     */
    @XmlEnumValue("shipments")
    SHIPMENTS("shipments"),

    /**
     * Elektronická evidence tržeb.
     * 
     */
    @XmlEnumValue("electronicRecordsOfSales")
    ELECTRONIC_RECORDS_OF_SALES("electronicRecordsOfSales"),

    /**
     * Evidence náhradního plnění.
     * 
     */
    @XmlEnumValue("registerOfCure")
    REGISTER_OF_CURE("registerOfCure"),

    /**
     * Tuzemské cestovní příkazy.
     * 
     */
    @XmlEnumValue("domesticTravelOrder")
    DOMESTIC_TRAVEL_ORDER("domesticTravelOrder"),

    /**
     * Zahraniční cestovní příkazy.
     * 
     */
    @XmlEnumValue("foreignTravelOrders")
    FOREIGN_TRAVEL_ORDERS("foreignTravelOrders");
    private final String value;

    AgendaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgendaType fromValue(String v) {
        for (AgendaType c: AgendaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
