//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for agendaMovementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="agendaMovementType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="issuedInvoice"/&gt;
 *     &lt;enumeration value="receivedInvoice"/&gt;
 *     &lt;enumeration value="receiptVoucher"/&gt;
 *     &lt;enumeration value="issueSlip"/&gt;
 *     &lt;enumeration value="transfer"/&gt;
 *     &lt;enumeration value="production"/&gt;
 *     &lt;enumeration value="saleVoucher"/&gt;
 *     &lt;enumeration value="voucher"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "agendaMovementType")
@XmlEnum
public enum AgendaMovementType {


    /**
     * Vydaná faktura.
     * 
     */
    @XmlEnumValue("issuedInvoice")
    ISSUED_INVOICE("issuedInvoice"),

    /**
     * Přijatá faktura.
     * 
     */
    @XmlEnumValue("receivedInvoice")
    RECEIVED_INVOICE("receivedInvoice"),

    /**
     * Příjemka.
     * 
     */
    @XmlEnumValue("receiptVoucher")
    RECEIPT_VOUCHER("receiptVoucher"),

    /**
     * Výdejka.
     * 
     */
    @XmlEnumValue("issueSlip")
    ISSUE_SLIP("issueSlip"),

    /**
     * Převodka.
     * 
     */
    @XmlEnumValue("transfer")
    TRANSFER("transfer"),

    /**
     * Výroba.
     * 
     */
    @XmlEnumValue("production")
    PRODUCTION("production"),

    /**
     * Prodejka.
     * 
     */
    @XmlEnumValue("saleVoucher")
    SALE_VOUCHER("saleVoucher"),

    /**
     * Pokladní doklad.
     * 
     */
    @XmlEnumValue("voucher")
    VOUCHER("voucher");
    private final String value;

    AgendaMovementType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgendaMovementType fromValue(String v) {
        for (AgendaMovementType c: AgendaMovementType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
