//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctrlType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ctrlType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="text"/&gt;
 *     &lt;enumeration value="push"/&gt;
 *     &lt;enumeration value="link"/&gt;
 *     &lt;enumeration value="group"/&gt;
 *     &lt;enumeration value="rect"/&gt;
 *     &lt;enumeration value="image"/&gt;
 *     &lt;enumeration value="edit"/&gt;
 *     &lt;enumeration value="check"/&gt;
 *     &lt;enumeration value="pick"/&gt;
 *     &lt;enumeration value="list"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ctrlType")
@XmlEnum
public enum CtrlType {


    /**
     * Popis.
     * 
     */
    @XmlEnumValue("text")
    TEXT("text"),

    /**
     * Tlačítko.
     * 
     */
    @XmlEnumValue("push")
    PUSH("push"),

    /**
     * Odkaz.
     * 
     */
    @XmlEnumValue("link")
    LINK("link"),

    /**
     * Rámeček skupiny.
     * 
     */
    @XmlEnumValue("group")
    GROUP("group"),

    /**
     * Rámeček.
     * 
     */
    @XmlEnumValue("rect")
    RECT("rect"),

    /**
     * Obrázek.
     * 
     */
    @XmlEnumValue("image")
    IMAGE("image"),

    /**
     * Textové pole.
     * 
     */
    @XmlEnumValue("edit")
    EDIT("edit"),

    /**
     * Zaškrtávací pole.
     * 
     */
    @XmlEnumValue("check")
    CHECK("check"),

    /**
     * Datumové pole.
     * 
     */
    @XmlEnumValue("pick")
    PICK("pick"),

    /**
     * Seznamové pole.
     * 
     */
    @XmlEnumValue("list")
    LIST("list");
    private final String value;

    CtrlType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CtrlType fromValue(String v) {
        for (CtrlType c: CtrlType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
