//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EETmodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="EETmodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="current"/&gt;
 *     &lt;enumeration value="simplified"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EETmodeType")
@XmlEnum
public enum EETmodeType {


    /**
     * Běžný.
     * 
     */
    @XmlEnumValue("current")
    CURRENT("current"),

    /**
     * Zjednodušený.
     * 
     */
    @XmlEnumValue("simplified")
    SIMPLIFIED("simplified");
    private final String value;

    EETmodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EETmodeType fromValue(String v) {
        for (EETmodeType c: EETmodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
