//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Elektronická evidence tržeb. Jen CZ verze.
 * 
 * <p>Java class for EETType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EETType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stateEET" type="{http://www.stormware.cz/schema/version_2/type.xsd}stateEETType"/&gt;
 *         &lt;element name="detailEET" type="{http://www.stormware.cz/schema/version_2/type.xsd}detailEETType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="profile" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EETType", propOrder = {
    "stateEET",
    "detailEET",
    "profile"
})
public class EETType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StateEETType stateEET;
    protected List<DetailEETType> detailEET;
    protected RefType profile;

    /**
     * Gets the value of the stateEET property.
     * 
     * @return
     *     possible object is
     *     {@link StateEETType }
     *     
     */
    public StateEETType getStateEET() {
        return stateEET;
    }

    /**
     * Sets the value of the stateEET property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateEETType }
     *     
     */
    public void setStateEET(StateEETType value) {
        this.stateEET = value;
    }

    /**
     * Gets the value of the detailEET property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the detailEET property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetailEET().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetailEETType }
     * 
     * 
     */
    public List<DetailEETType> getDetailEET() {
        if (detailEET == null) {
            detailEET = new ArrayList<DetailEETType>();
        }
        return this.detailEET;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setProfile(RefType value) {
        this.profile = value;
    }

}
