//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for guaranteeTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="guaranteeTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="hour"/&gt;
 *     &lt;enumeration value="day"/&gt;
 *     &lt;enumeration value="month"/&gt;
 *     &lt;enumeration value="year"/&gt;
 *     &lt;enumeration value="life"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "guaranteeTypeType")
@XmlEnum
public enum GuaranteeTypeType {


    /**
     * Bez záruky.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Záruka je uvedena v hodinách.
     * 
     */
    @XmlEnumValue("hour")
    HOUR("hour"),

    /**
     * Záruka je uvedena v dnech.
     * 
     */
    @XmlEnumValue("day")
    DAY("day"),

    /**
     * Záruka je uvedena v měsících.
     * 
     */
    @XmlEnumValue("month")
    MONTH("month"),

    /**
     * Záruka je uvedena v rocích.
     * 
     */
    @XmlEnumValue("year")
    YEAR("year"),

    /**
     * Doživotní záruka.
     * 
     */
    @XmlEnumValue("life")
    LIFE("life");
    private final String value;

    GuaranteeTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GuaranteeTypeType fromValue(String v) {
        for (GuaranteeTypeType c: GuaranteeTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
