//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for liquidatedDocumentAgendaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="liquidatedDocumentAgendaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="issuedInvoice"/&gt;
 *     &lt;enumeration value="receivedInvoice"/&gt;
 *     &lt;enumeration value="receivable"/&gt;
 *     &lt;enumeration value="commitment"/&gt;
 *     &lt;enumeration value="issuedAdvanceInvoice"/&gt;
 *     &lt;enumeration value="receivedAdvanceInvoice"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "liquidatedDocumentAgendaType")
@XmlEnum
public enum LiquidatedDocumentAgendaType {


    /**
     * Agenda Vydané faktury.
     * 
     */
    @XmlEnumValue("issuedInvoice")
    ISSUED_INVOICE("issuedInvoice"),

    /**
     * Agenda Přijaté faktury.
     * 
     */
    @XmlEnumValue("receivedInvoice")
    RECEIVED_INVOICE("receivedInvoice"),

    /**
     * Agenda Ostatní pohledávky.
     * 
     */
    @XmlEnumValue("receivable")
    RECEIVABLE("receivable"),

    /**
     * Agenda Ostatní závazky.
     * 
     */
    @XmlEnumValue("commitment")
    COMMITMENT("commitment"),

    /**
     * Agenda Vydané zálohové faktury.
     * 
     */
    @XmlEnumValue("issuedAdvanceInvoice")
    ISSUED_ADVANCE_INVOICE("issuedAdvanceInvoice"),

    /**
     * Agenda Přijaté zálohové faktury.
     * 
     */
    @XmlEnumValue("receivedAdvanceInvoice")
    RECEIVED_ADVANCE_INVOICE("receivedAdvanceInvoice");
    private final String value;

    LiquidatedDocumentAgendaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LiquidatedDocumentAgendaType fromValue(String v) {
        for (LiquidatedDocumentAgendaType c: LiquidatedDocumentAgendaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
