//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for myAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="myAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="address" type="{http://www.stormware.cz/schema/version_2/type.xsd}addressInternetType"/&gt;
 *         &lt;element name="establishment" type="{http://www.stormware.cz/schema/version_2/type.xsd}establishmentType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "myAddress", propOrder = {

})
public class MyAddress {

    @XmlElement(required = true)
    protected AddressInternetType address;
    protected EstablishmentType establishment;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInternetType }
     *     
     */
    public AddressInternetType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInternetType }
     *     
     */
    public void setAddress(AddressInternetType value) {
        this.address = value;
    }

    /**
     * Gets the value of the establishment property.
     * 
     * @return
     *     possible object is
     *     {@link EstablishmentType }
     *     
     */
    public EstablishmentType getEstablishment() {
        return establishment;
    }

    /**
     * Sets the value of the establishment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstablishmentType }
     *     
     */
    public void setEstablishment(EstablishmentType value) {
        this.establishment = value;
    }

}
