//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Data volitelného parametru.
 * 
 * <p>Java class for parameterDocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameterDocType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.stormware.cz/schema/version_2/type.xsd}string16"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="textValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="memoValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="currencyValue" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType"/&gt;
 *           &lt;element name="booleanValue" type="{http://www.stormware.cz/schema/version_2/type.xsd}boolean"/&gt;
 *           &lt;element name="numberValue" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *           &lt;element name="datetimeValue" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *           &lt;element name="listValueRef" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType"/&gt;
 *           &lt;element name="integerValue" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="list" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterDocType", propOrder = {
    "name",
    "textValue",
    "memoValue",
    "currencyValue",
    "booleanValue",
    "numberValue",
    "datetimeValue",
    "listValueRef",
    "integerValue",
    "list"
})
public class ParameterDocType {

    @XmlElement(required = true)
    protected String name;
    protected String textValue;
    protected String memoValue;
    protected Double currencyValue;
    @XmlSchemaType(name = "string")
    protected Boolean booleanValue;
    protected Float numberValue;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datetimeValue;
    protected RefType listValueRef;
    protected BigInteger integerValue;
    protected RefType list;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the textValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextValue() {
        return textValue;
    }

    /**
     * Sets the value of the textValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextValue(String value) {
        this.textValue = value;
    }

    /**
     * Gets the value of the memoValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemoValue() {
        return memoValue;
    }

    /**
     * Sets the value of the memoValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemoValue(String value) {
        this.memoValue = value;
    }

    /**
     * Gets the value of the currencyValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCurrencyValue() {
        return currencyValue;
    }

    /**
     * Sets the value of the currencyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCurrencyValue(Double value) {
        this.currencyValue = value;
    }

    /**
     * Gets the value of the booleanValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBooleanValue() {
        return booleanValue;
    }

    /**
     * Sets the value of the booleanValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBooleanValue(Boolean value) {
        this.booleanValue = value;
    }

    /**
     * Gets the value of the numberValue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNumberValue() {
        return numberValue;
    }

    /**
     * Sets the value of the numberValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNumberValue(Float value) {
        this.numberValue = value;
    }

    /**
     * Gets the value of the datetimeValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetimeValue() {
        return datetimeValue;
    }

    /**
     * Sets the value of the datetimeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetimeValue(XMLGregorianCalendar value) {
        this.datetimeValue = value;
    }

    /**
     * Gets the value of the listValueRef property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getListValueRef() {
        return listValueRef;
    }

    /**
     * Sets the value of the listValueRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setListValueRef(RefType value) {
        this.listValueRef = value;
    }

    /**
     * Gets the value of the integerValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIntegerValue() {
        return integerValue;
    }

    /**
     * Sets the value of the integerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIntegerValue(BigInteger value) {
        this.integerValue = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setList(RefType value) {
        this.list = value;
    }

}
