//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parameterAgendaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="parameterAgendaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="adresar"/&gt;
 *     &lt;enumeration value="udalosti"/&gt;
 *     &lt;enumeration value="pokladna"/&gt;
 *     &lt;enumeration value="banka"/&gt;
 *     &lt;enumeration value="interni"/&gt;
 *     &lt;enumeration value="nabidky"/&gt;
 *     &lt;enumeration value="poptavky"/&gt;
 *     &lt;enumeration value="objednavky"/&gt;
 *     &lt;enumeration value="faktury"/&gt;
 *     &lt;enumeration value="zasoby"/&gt;
 *     &lt;enumeration value="prijemky"/&gt;
 *     &lt;enumeration value="vydejky"/&gt;
 *     &lt;enumeration value="vyroba"/&gt;
 *     &lt;enumeration value="prevod"/&gt;
 *     &lt;enumeration value="agenda"/&gt;
 *     &lt;enumeration value="personalistika"/&gt;
 *     &lt;enumeration value="pracovniPomery"/&gt;
 *     &lt;enumeration value="drobnyMajetek"/&gt;
 *     &lt;enumeration value="majetek"/&gt;
 *     &lt;enumeration value="leasingovyMajetek"/&gt;
 *     &lt;enumeration value="smlouvy"/&gt;
 *     &lt;enumeration value="vozidla"/&gt;
 *     &lt;enumeration value="ridici"/&gt;
 *     &lt;enumeration value="jizdy"/&gt;
 *     &lt;enumeration value="seznam"/&gt;
 *     &lt;enumeration value="osnova"/&gt;
 *     &lt;enumeration value="reklamace"/&gt;
 *     &lt;enumeration value="servis"/&gt;
 *     &lt;enumeration value="strediska"/&gt;
 *     &lt;enumeration value="cinnosti"/&gt;
 *     &lt;enumeration value="zakazky"/&gt;
 *     &lt;enumeration value="prodejky"/&gt;
 *     &lt;enumeration value="ciselneRady"/&gt;
 *     &lt;enumeration value="evidencniCisla"/&gt;
 *     &lt;enumeration value="penezniDenik"/&gt;
 *     &lt;enumeration value="ucetniDenik"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "parameterAgendaType")
@XmlEnum
public enum ParameterAgendaType {


    /**
     * Parametry agendy Adresář.
     * 
     */
    @XmlEnumValue("adresar")
    ADRESAR("adresar"),

    /**
     * Parametry agendy Události.
     * 
     */
    @XmlEnumValue("udalosti")
    UDALOSTI("udalosti"),

    /**
     * Parametry agendy Pokladna.
     * 
     */
    @XmlEnumValue("pokladna")
    POKLADNA("pokladna"),

    /**
     * Parametry agendy Banka.
     * 
     */
    @XmlEnumValue("banka")
    BANKA("banka"),

    /**
     * Parametry agendy Interní doklady.
     * 
     */
    @XmlEnumValue("interni")
    INTERNI("interni"),

    /**
     * Parametry agendy Nabídky.
     * 
     */
    @XmlEnumValue("nabidky")
    NABIDKY("nabidky"),

    /**
     * Parametry agendy Poptávky.
     * 
     */
    @XmlEnumValue("poptavky")
    POPTAVKY("poptavky"),

    /**
     * Parametry agendy Objednávky.
     * 
     */
    @XmlEnumValue("objednavky")
    OBJEDNAVKY("objednavky"),

    /**
     * Parametry agendy Faktury.
     * 
     */
    @XmlEnumValue("faktury")
    FAKTURY("faktury"),

    /**
     * Parametry agendy Zásoby.
     * 
     */
    @XmlEnumValue("zasoby")
    ZASOBY("zasoby"),

    /**
     * Parametry agendy Příjemky.
     * 
     */
    @XmlEnumValue("prijemky")
    PRIJEMKY("prijemky"),

    /**
     * Parametry agendy Výdejky.
     * 
     */
    @XmlEnumValue("vydejky")
    VYDEJKY("vydejky"),

    /**
     * Parametry agendy Výroba.
     * 
     */
    @XmlEnumValue("vyroba")
    VYROBA("vyroba"),

    /**
     * Parametry agendy Převod.
     * 
     */
    @XmlEnumValue("prevod")
    PREVOD("prevod"),

    /**
     * Parametry uživatelské agendy.
     * 
     */
    @XmlEnumValue("agenda")
    AGENDA("agenda"),

    /**
     * Parametry agendy Personalistika.
     * 
     */
    @XmlEnumValue("personalistika")
    PERSONALISTIKA("personalistika"),

    /**
     * Parametry agendy Pracovní poměry (pouze SK verze).
     * 
     */
    @XmlEnumValue("pracovniPomery")
    PRACOVNI_POMERY("pracovniPomery"),

    /**
     * Parametry agendy Drobný majetek.
     * 
     */
    @XmlEnumValue("drobnyMajetek")
    DROBNY_MAJETEK("drobnyMajetek"),

    /**
     * Parametry agendy Majetek.
     * 
     */
    @XmlEnumValue("majetek")
    MAJETEK("majetek"),

    /**
     * Parametry agendy Leasingový majetek.
     * 
     */
    @XmlEnumValue("leasingovyMajetek")
    LEASINGOVY_MAJETEK("leasingovyMajetek"),

    /**
     * Parametry agendy Smlouvy.
     * 
     */
    @XmlEnumValue("smlouvy")
    SMLOUVY("smlouvy"),

    /**
     * Parametry agendy Vozidla.
     * 
     */
    @XmlEnumValue("vozidla")
    VOZIDLA("vozidla"),

    /**
     * Parametry agendy Seznam řidičů.
     * 
     */
    @XmlEnumValue("ridici")
    RIDICI("ridici"),

    /**
     * Parametry agendy Jízdy.
     * 
     */
    @XmlEnumValue("jizdy")
    JIZDY("jizdy"),

    /**
     * Parametry uživatelského seznamu. (není připraveno)
     * 
     */
    @XmlEnumValue("seznam")
    SEZNAM("seznam"),

    /**
     * Parametry agendy Účtová osnova.
     * 
     */
    @XmlEnumValue("osnova")
    OSNOVA("osnova"),

    /**
     * Parametry agendy Reklamace.
     * 
     */
    @XmlEnumValue("reklamace")
    REKLAMACE("reklamace"),

    /**
     * Parametry agendy Servis.
     * 
     */
    @XmlEnumValue("servis")
    SERVIS("servis"),

    /**
     * Parametry agendy Střediska.
     * 
     */
    @XmlEnumValue("strediska")
    STREDISKA("strediska"),

    /**
     * Parametry agendy Činnosti.
     * 
     */
    @XmlEnumValue("cinnosti")
    CINNOSTI("cinnosti"),

    /**
     * Parametry agendy Zakázky.
     * 
     */
    @XmlEnumValue("zakazky")
    ZAKAZKY("zakazky"),

    /**
     * Parametry agendy Prodejky.
     * 
     */
    @XmlEnumValue("prodejky")
    PRODEJKY("prodejky"),

    /**
     * Parametry agendy Číselné řady.
     * 
     */
    @XmlEnumValue("ciselneRady")
    CISELNE_RADY("ciselneRady"),

    /**
     * Parametry agendy Evidenční čísla.
     * 
     */
    @XmlEnumValue("evidencniCisla")
    EVIDENCNI_CISLA("evidencniCisla"),

    /**
     * Parametry agendy Peněžní deník (JU).
     * 
     */
    @XmlEnumValue("penezniDenik")
    PENEZNI_DENIK("penezniDenik"),

    /**
     * Parametry agendy Účetní deník (PU).
     * 
     */
    @XmlEnumValue("ucetniDenik")
    UCETNI_DENIK("ucetniDenik");
    private final String value;

    ParameterAgendaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParameterAgendaType fromValue(String v) {
        for (ParameterAgendaType c: ParameterAgendaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
