//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recyclingContribType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recyclingContribType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="recyclingContribType" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="recyclingContribText" type="{http://www.stormware.cz/schema/version_2/type.xsd}string64" minOccurs="0"/&gt;
 *         &lt;element name="recyclingContribAmount" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="recyclingContribUnit" type="{http://www.stormware.cz/schema/version_2/type.xsd}unitType" minOccurs="0"/&gt;
 *         &lt;element name="coefficientOfRecyclingContrib" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recyclingContribType", propOrder = {
    "recyclingContribType",
    "recyclingContribText",
    "recyclingContribAmount",
    "recyclingContribUnit",
    "coefficientOfRecyclingContrib"
})
public class RecyclingContribType {

    protected RefType recyclingContribType;
    protected String recyclingContribText;
    protected Double recyclingContribAmount;
    protected String recyclingContribUnit;
    @XmlElementRef(name = "coefficientOfRecyclingContrib", namespace = "http://www.stormware.cz/schema/version_2/type.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Float> coefficientOfRecyclingContrib;

    /**
     * Gets the value of the recyclingContribType property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getRecyclingContribType() {
        return recyclingContribType;
    }

    /**
     * Sets the value of the recyclingContribType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setRecyclingContribType(RefType value) {
        this.recyclingContribType = value;
    }

    /**
     * Gets the value of the recyclingContribText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecyclingContribText() {
        return recyclingContribText;
    }

    /**
     * Sets the value of the recyclingContribText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecyclingContribText(String value) {
        this.recyclingContribText = value;
    }

    /**
     * Gets the value of the recyclingContribAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRecyclingContribAmount() {
        return recyclingContribAmount;
    }

    /**
     * Sets the value of the recyclingContribAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRecyclingContribAmount(Double value) {
        this.recyclingContribAmount = value;
    }

    /**
     * Gets the value of the recyclingContribUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecyclingContribUnit() {
        return recyclingContribUnit;
    }

    /**
     * Sets the value of the recyclingContribUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecyclingContribUnit(String value) {
        this.recyclingContribUnit = value;
    }

    /**
     * Gets the value of the coefficientOfRecyclingContrib property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public JAXBElement<Float> getCoefficientOfRecyclingContrib() {
        return coefficientOfRecyclingContrib;
    }

    /**
     * Sets the value of the coefficientOfRecyclingContrib property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Float }{@code >}
     *     
     */
    public void setCoefficientOfRecyclingContrib(JAXBElement<Float> value) {
        this.coefficientOfRecyclingContrib = value;
    }

}
