//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsSourceDocumentOrderItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingsSourceDocumentOrderItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="linkOrderItemToInvoice" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkOrderItemToInvoiceType"/&gt;
 *         &lt;element name="linkOrderItemToIssueSlip" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkOrderItemToIssueSlipType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingsSourceDocumentOrderItemType", propOrder = {
    "linkOrderItemToInvoice",
    "linkOrderItemToIssueSlip"
})
public class SettingsSourceDocumentOrderItemType {

    @XmlElement(defaultValue = "4")
    protected String linkOrderItemToInvoice;
    @XmlElement(defaultValue = "4")
    protected String linkOrderItemToIssueSlip;

    /**
     * Gets the value of the linkOrderItemToInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkOrderItemToInvoice() {
        return linkOrderItemToInvoice;
    }

    /**
     * Sets the value of the linkOrderItemToInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkOrderItemToInvoice(String value) {
        this.linkOrderItemToInvoice = value;
    }

    /**
     * Gets the value of the linkOrderItemToIssueSlip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkOrderItemToIssueSlip() {
        return linkOrderItemToIssueSlip;
    }

    /**
     * Sets the value of the linkOrderItemToIssueSlip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkOrderItemToIssueSlip(String value) {
        this.linkOrderItemToIssueSlip = value;
    }

}
