//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsSourceDocumentItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingsSourceDocumentItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="linkIssueSlipItemToInvoice" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkIssueSlipItemToInvoiceType"/&gt;
 *         &lt;element name="linkIssueOfferItemToReceivedOrder" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkIssueOfferItemToReceivedOrderType"/&gt;
 *         &lt;element name="linkReceivedOrderItemToTransfer" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkReceivedOrderItemToTransferType"/&gt;
 *         &lt;element name="linkReceivedOrderItemToSaleVoucher" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkReceivedOrderItemToSaleVoucherType"/&gt;
 *         &lt;element name="linkIssueSlipItemToSaleVoucher" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkIssueSlipItemToSaleVoucherType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingsSourceDocumentItemType", propOrder = {
    "linkIssueSlipItemToInvoice",
    "linkIssueOfferItemToReceivedOrder",
    "linkReceivedOrderItemToTransfer",
    "linkReceivedOrderItemToSaleVoucher",
    "linkIssueSlipItemToSaleVoucher"
})
public class SettingsSourceDocumentItemType {

    @XmlElement(defaultValue = "4")
    protected String linkIssueSlipItemToInvoice;
    @XmlElement(defaultValue = "4")
    protected String linkIssueOfferItemToReceivedOrder;
    @XmlElement(defaultValue = "4")
    protected String linkReceivedOrderItemToTransfer;
    @XmlElement(defaultValue = "4")
    protected String linkReceivedOrderItemToSaleVoucher;
    @XmlElement(defaultValue = "4")
    protected String linkIssueSlipItemToSaleVoucher;

    /**
     * Gets the value of the linkIssueSlipItemToInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIssueSlipItemToInvoice() {
        return linkIssueSlipItemToInvoice;
    }

    /**
     * Sets the value of the linkIssueSlipItemToInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIssueSlipItemToInvoice(String value) {
        this.linkIssueSlipItemToInvoice = value;
    }

    /**
     * Gets the value of the linkIssueOfferItemToReceivedOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIssueOfferItemToReceivedOrder() {
        return linkIssueOfferItemToReceivedOrder;
    }

    /**
     * Sets the value of the linkIssueOfferItemToReceivedOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIssueOfferItemToReceivedOrder(String value) {
        this.linkIssueOfferItemToReceivedOrder = value;
    }

    /**
     * Gets the value of the linkReceivedOrderItemToTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkReceivedOrderItemToTransfer() {
        return linkReceivedOrderItemToTransfer;
    }

    /**
     * Sets the value of the linkReceivedOrderItemToTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkReceivedOrderItemToTransfer(String value) {
        this.linkReceivedOrderItemToTransfer = value;
    }

    /**
     * Gets the value of the linkReceivedOrderItemToSaleVoucher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkReceivedOrderItemToSaleVoucher() {
        return linkReceivedOrderItemToSaleVoucher;
    }

    /**
     * Sets the value of the linkReceivedOrderItemToSaleVoucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkReceivedOrderItemToSaleVoucher(String value) {
        this.linkReceivedOrderItemToSaleVoucher = value;
    }

    /**
     * Gets the value of the linkIssueSlipItemToSaleVoucher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIssueSlipItemToSaleVoucher() {
        return linkIssueSlipItemToSaleVoucher;
    }

    /**
     * Sets the value of the linkIssueSlipItemToSaleVoucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIssueSlipItemToSaleVoucher(String value) {
        this.linkIssueSlipItemToSaleVoucher = value;
    }

}
