//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsSourceDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingsSourceDocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="linkOrderToAdvanceInvoice" type="{http://www.stormware.cz/schema/version_2/type.xsd}linkOrderToAdvanceInvoiceType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingsSourceDocumentType", propOrder = {
    "linkOrderToAdvanceInvoice"
})
public class SettingsSourceDocumentType {

    @XmlElement(defaultValue = "3")
    protected String linkOrderToAdvanceInvoice;

    /**
     * Gets the value of the linkOrderToAdvanceInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkOrderToAdvanceInvoice() {
        return linkOrderToAdvanceInvoice;
    }

    /**
     * Sets the value of the linkOrderToAdvanceInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkOrderToAdvanceInvoice(String value) {
        this.linkOrderToAdvanceInvoice = value;
    }

}
