//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stateEETType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="stateEETType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="notEnter"/&gt;
 *     &lt;enumeration value="notSend"/&gt;
 *     &lt;enumeration value="forSending"/&gt;
 *     &lt;enumeration value="externally"/&gt;
 *     &lt;enumeration value="simplify"/&gt;
 *     &lt;enumeration value="sent"/&gt;
 *     &lt;enumeration value="invalidData"/&gt;
 *     &lt;enumeration value="commError"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "stateEETType")
@XmlEnum
public enum StateEETType {


    /**
     * Doklad nesplňuje podmínky pro vstup do EET (forma úhrady příkazem apod.).
     * 
     */
    @XmlEnumValue("notEnter")
    NOT_ENTER("notEnter"),

    /**
     * Neodesílat do EET. Uživatel určil změnou stavu, že i když doklad plní podmínky pro vstup do EET, nechce jej tam odeslat.
     * 
     */
    @XmlEnumValue("notSend")
    NOT_SEND("notSend"),

    /**
     * K odeslání do EET.
     * 
     */
    @XmlEnumValue("forSending")
    FOR_SENDING("forSending"),

    /**
     * Odesláno do EET mimo program POHODA.
     * 
     */
    @XmlEnumValue("externally")
    EXTERNALLY("externally"),

    /**
     * Vytištěný doklad neodeslaný do EET - v zjednodušeném režimu. Pouze pro export.
     * 
     */
    @XmlEnumValue("simplify")
    SIMPLIFY("simplify"),

    /**
     * Doklad je již odeslán do EET. Pouze pro export.
     * 
     */
    @XmlEnumValue("sent")
    SENT("sent"),

    /**
     * Při skladbě věty pro EET došlo k chybě, nebo server FS vrátil chybové hlášení poukazující na chybu dat. Pouze pro export.
     * 
     */
    @XmlEnumValue("invalidData")
    INVALID_DATA("invalidData"),

    /**
     * Při komunikaci na server došlo k chybě. Pouze pro export.
     * 
     */
    @XmlEnumValue("commError")
    COMM_ERROR("commError");
    private final String value;

    StateEETType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StateEETType fromValue(String v) {
        for (StateEETType c: StateEETType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
