//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stavType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="stavType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ok"/&gt;
 *     &lt;enumeration value="warning"/&gt;
 *     &lt;enumeration value="error"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "stavType")
@XmlEnum
public enum StavType {


    /**
     * Informace o zpracování.
     * 
     */
    @XmlEnumValue("ok")
    OK("ok"),

    /**
     * Varování.
     * 
     */
    @XmlEnumValue("warning")
    WARNING("warning"),

    /**
     * Chyba.
     * 
     */
    @XmlEnumValue("error")
    ERROR("error");
    private final String value;

    StavType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StavType fromValue(String v) {
        for (StavType c: StavType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
