//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Údaje skladové zásoby vložené do položky dokladu
 * 
 * <p>Java class for stockItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stockItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="store" type="{http://www.stormware.cz/schema/version_2/type.xsd}refType" minOccurs="0"/&gt;
 *         &lt;element name="stockItem" type="{http://www.stormware.cz/schema/version_2/type.xsd}stockRefType"/&gt;
 *         &lt;element name="serialNumber" type="{http://www.stormware.cz/schema/version_2/type.xsd}serialNumberType" minOccurs="0"/&gt;
 *         &lt;element name="serialNumberExtId" type="{http://www.stormware.cz/schema/version_2/type.xsd}extIdType" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stockItemType", propOrder = {

})
public class StockItemType {

    protected RefType store;
    @XmlElement(required = true)
    protected StockRefType stockItem;
    protected String serialNumber;
    protected ExtIdType serialNumberExtId;

    /**
     * Gets the value of the store property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getStore() {
        return store;
    }

    /**
     * Sets the value of the store property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setStore(RefType value) {
        this.store = value;
    }

    /**
     * Gets the value of the stockItem property.
     * 
     * @return
     *     possible object is
     *     {@link StockRefType }
     *     
     */
    public StockRefType getStockItem() {
        return stockItem;
    }

    /**
     * Sets the value of the stockItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link StockRefType }
     *     
     */
    public void setStockItem(StockRefType value) {
        this.stockItem = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the serialNumberExtId property.
     * 
     * @return
     *     possible object is
     *     {@link ExtIdType }
     *     
     */
    public ExtIdType getSerialNumberExtId() {
        return serialNumberExtId;
    }

    /**
     * Sets the value of the serialNumberExtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtIdType }
     *     
     */
    public void setSerialNumberExtId(ExtIdType value) {
        this.serialNumberExtId = value;
    }

}
