//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRoundingVAT_CZ_old.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="typeRoundingVAT_CZ_old"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="up2tenthEveryItem"/&gt;
 *     &lt;enumeration value="up2tenthEveryRate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeRoundingVAT_CZ_old")
@XmlEnum
public enum TypeRoundingVATCZOld {


    /**
     * Zaokrouhlit DPH na každé položce, v CZ se nepoužívá po 1.1.2005.
     * 
     */
    @XmlEnumValue("up2tenthEveryItem")
    UP_2_TENTH_EVERY_ITEM("up2tenthEveryItem"),

    /**
     * Zaokrouhlit součet DPH v každé sazbě, v CZ se nepoužívá po 1.1.2005.
     * 
     */
    @XmlEnumValue("up2tenthEveryRate")
    UP_2_TENTH_EVERY_RATE("up2tenthEveryRate");
    private final String value;

    TypeRoundingVATCZOld(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRoundingVATCZOld fromValue(String v) {
        for (TypeRoundingVATCZOld c: TypeRoundingVATCZOld.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
