//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRoundingVAT_CZ.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="typeRoundingVAT_CZ"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="math2tenthEveryItem"/&gt;
 *     &lt;enumeration value="math2halfEveryItem"/&gt;
 *     &lt;enumeration value="math2intEveryItem"/&gt;
 *     &lt;enumeration value="noneEveryRate"/&gt;
 *     &lt;enumeration value="math2tenthEveryRate"/&gt;
 *     &lt;enumeration value="math2halfEveryRate"/&gt;
 *     &lt;enumeration value="math2intEveryRate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeRoundingVAT_CZ")
@XmlEnum
public enum TypeRoundingVATCZ {


    /**
     * DPH nezaokrouhlovat.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Matematicky zaokrouhlit na 10h.
     * 
     */
    @XmlEnumValue("math2tenthEveryItem")
    MATH_2_TENTH_EVERY_ITEM("math2tenthEveryItem"),

    /**
     * Matematicky zaokrouhlit na 50h.
     * 
     */
    @XmlEnumValue("math2halfEveryItem")
    MATH_2_HALF_EVERY_ITEM("math2halfEveryItem"),

    /**
     * Matematicky zaokrouhlit na koruny.
     * 
     */
    @XmlEnumValue("math2intEveryItem")
    MATH_2_INT_EVERY_ITEM("math2intEveryItem"),

    /**
     * DPH v každé sazbě nezaokrouhlovat.
     * 
     */
    @XmlEnumValue("noneEveryRate")
    NONE_EVERY_RATE("noneEveryRate"),

    /**
     * Zaokr. DPH v každé sazbě, mat. na 10h.
     * 
     */
    @XmlEnumValue("math2tenthEveryRate")
    MATH_2_TENTH_EVERY_RATE("math2tenthEveryRate"),

    /**
     * Zaokr. DPH v každé sazbě, mat. na 50h.
     * 
     */
    @XmlEnumValue("math2halfEveryRate")
    MATH_2_HALF_EVERY_RATE("math2halfEveryRate"),

    /**
     * Zaokr. DPH v každé sazbě, mat. na koruny.
     * 
     */
    @XmlEnumValue("math2intEveryRate")
    MATH_2_INT_EVERY_RATE("math2intEveryRate");
    private final String value;

    TypeRoundingVATCZ(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRoundingVATCZ fromValue(String v) {
        for (TypeRoundingVATCZ c: TypeRoundingVATCZ.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
