//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRoundingVAT_SK.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="typeRoundingVAT_SK"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="noneEveryRate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeRoundingVAT_SK")
@XmlEnum
public enum TypeRoundingVATSK {


    /**
     * DPH nezaokrouhlovat.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Zaokrúhliť súčet DPH v každej sadzbe.
     * 
     */
    @XmlEnumValue("noneEveryRate")
    NONE_EVERY_RATE("noneEveryRate");
    private final String value;

    TypeRoundingVATSK(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRoundingVATSK fromValue(String v) {
        for (TypeRoundingVATSK c: TypeRoundingVATSK.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
