//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCurrencyHome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeCurrencyHome"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="priceNone" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceLow" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceLowVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceLowSum" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceHigh" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceHighVAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="priceHighSum" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="price3" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="price3VAT" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="price3Sum" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType" minOccurs="0"/&gt;
 *         &lt;element name="round" type="{http://www.stormware.cz/schema/version_2/type.xsd}typeRound" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeCurrencyHome", propOrder = {

})
public class TypeCurrencyHome {

    protected Double priceNone;
    protected Double priceLow;
    protected Double priceLowVAT;
    protected Double priceLowSum;
    protected Double priceHigh;
    protected Double priceHighVAT;
    protected Double priceHighSum;
    protected Double price3;
    protected Double price3VAT;
    protected Double price3Sum;
    protected TypeRound round;

    /**
     * Gets the value of the priceNone property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceNone() {
        return priceNone;
    }

    /**
     * Sets the value of the priceNone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceNone(Double value) {
        this.priceNone = value;
    }

    /**
     * Gets the value of the priceLow property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceLow() {
        return priceLow;
    }

    /**
     * Sets the value of the priceLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceLow(Double value) {
        this.priceLow = value;
    }

    /**
     * Gets the value of the priceLowVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceLowVAT() {
        return priceLowVAT;
    }

    /**
     * Sets the value of the priceLowVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceLowVAT(Double value) {
        this.priceLowVAT = value;
    }

    /**
     * Gets the value of the priceLowSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceLowSum() {
        return priceLowSum;
    }

    /**
     * Sets the value of the priceLowSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceLowSum(Double value) {
        this.priceLowSum = value;
    }

    /**
     * Gets the value of the priceHigh property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceHigh() {
        return priceHigh;
    }

    /**
     * Sets the value of the priceHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceHigh(Double value) {
        this.priceHigh = value;
    }

    /**
     * Gets the value of the priceHighVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceHighVAT() {
        return priceHighVAT;
    }

    /**
     * Sets the value of the priceHighVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceHighVAT(Double value) {
        this.priceHighVAT = value;
    }

    /**
     * Gets the value of the priceHighSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceHighSum() {
        return priceHighSum;
    }

    /**
     * Sets the value of the priceHighSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceHighSum(Double value) {
        this.priceHighSum = value;
    }

    /**
     * Gets the value of the price3 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrice3() {
        return price3;
    }

    /**
     * Sets the value of the price3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrice3(Double value) {
        this.price3 = value;
    }

    /**
     * Gets the value of the price3VAT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrice3VAT() {
        return price3VAT;
    }

    /**
     * Sets the value of the price3VAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrice3VAT(Double value) {
        this.price3VAT = value;
    }

    /**
     * Gets the value of the price3Sum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrice3Sum() {
        return price3Sum;
    }

    /**
     * Sets the value of the price3Sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrice3Sum(Double value) {
        this.price3Sum = value;
    }

    /**
     * Gets the value of the round property.
     * 
     * @return
     *     possible object is
     *     {@link TypeRound }
     *     
     */
    public TypeRound getRound() {
        return round;
    }

    /**
     * Sets the value of the round property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeRound }
     *     
     */
    public void setRound(TypeRound value) {
        this.round = value;
    }

}
