//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRound complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeRound"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="priceRound" type="{http://www.stormware.cz/schema/version_2/type.xsd}currencyType"/&gt;
 *         &lt;group ref="{http://www.stormware.cz/schema/version_2/type.xsd}myGroupOfRound"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeRound", propOrder = {
    "priceRound",
    "rateVATround",
    "priceRoundSum",
    "priceRoundSumVAT"
})
public class TypeRound {

    protected Double priceRound;
    protected Double rateVATround;
    protected Double priceRoundSum;
    protected Double priceRoundSumVAT;

    /**
     * Gets the value of the priceRound property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceRound() {
        return priceRound;
    }

    /**
     * Sets the value of the priceRound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceRound(Double value) {
        this.priceRound = value;
    }

    /**
     * Gets the value of the rateVATround property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRateVATround() {
        return rateVATround;
    }

    /**
     * Sets the value of the rateVATround property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRateVATround(Double value) {
        this.rateVATround = value;
    }

    /**
     * Gets the value of the priceRoundSum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceRoundSum() {
        return priceRoundSum;
    }

    /**
     * Sets the value of the priceRoundSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceRoundSum(Double value) {
        this.priceRoundSum = value;
    }

    /**
     * Gets the value of the priceRoundSumVAT property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceRoundSumVAT() {
        return priceRoundSumVAT;
    }

    /**
     * Sets the value of the priceRoundSumVAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceRoundSumVAT(Double value) {
        this.priceRoundSumVAT = value;
    }

}
