//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.type;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeRoundingDocument.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="typeRoundingDocument"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="math2one"/&gt;
 *     &lt;enumeration value="math2half"/&gt;
 *     &lt;enumeration value="math2tenth"/&gt;
 *     &lt;enumeration value="math5cent"/&gt;
 *     &lt;enumeration value="up2one"/&gt;
 *     &lt;enumeration value="up2half"/&gt;
 *     &lt;enumeration value="up2tenth"/&gt;
 *     &lt;enumeration value="down2one"/&gt;
 *     &lt;enumeration value="down2half"/&gt;
 *     &lt;enumeration value="down2tenth"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeRoundingDocument")
@XmlEnum
public enum TypeRoundingDocument {


    /**
     * Doklad nezaokrouhlovat
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Zaokrouhlení matematicky na koruny.
     * 
     */
    @XmlEnumValue("math2one")
    MATH_2_ONE("math2one"),

    /**
     * Zaokrouhlení matematicky na padesátníky.
     * 
     */
    @XmlEnumValue("math2half")
    MATH_2_HALF("math2half"),

    /**
     * Zaokrouhlení matematicky na desetníky.
     * 
     */
    @XmlEnumValue("math2tenth")
    MATH_2_TENTH("math2tenth"),

    /**
     * Zaokrouhlení celkové částky na pěticenty (pouze SK).
     * 
     */
    @XmlEnumValue("math5cent")
    MATH_5_CENT("math5cent"),

    /**
     * Zaokrouhlení nahoru na koruny.
     * 
     */
    @XmlEnumValue("up2one")
    UP_2_ONE("up2one"),

    /**
     * Zaokrouhlení nahoru na padesátníky.
     * 
     */
    @XmlEnumValue("up2half")
    UP_2_HALF("up2half"),

    /**
     * Zaokrouhlení nahoru na desetníky.
     * 
     */
    @XmlEnumValue("up2tenth")
    UP_2_TENTH("up2tenth"),

    /**
     * Zaokrouhlení dolů na koruny.
     * 
     */
    @XmlEnumValue("down2one")
    DOWN_2_ONE("down2one"),

    /**
     * Zaokrouhlení dolů na padesátníky.
     * 
     */
    @XmlEnumValue("down2half")
    DOWN_2_HALF("down2half"),

    /**
     * Zaokrouhlení dolů na desetníky.
     * 
     */
    @XmlEnumValue("down2tenth")
    DOWN_2_TENTH("down2tenth");
    private final String value;

    TypeRoundingDocument(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeRoundingDocument fromValue(String v) {
        for (TypeRoundingDocument c: TypeRoundingDocument.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
