//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.filter;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for isdocAgendaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="isdocAgendaType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="interni_doklady"/&gt;
 *     &lt;enumeration value="vydane_faktury"/&gt;
 *     &lt;enumeration value="vydane_zalohove_faktury"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "isdocAgendaType")
@XmlEnum
public enum IsdocAgendaType {

    @XmlEnumValue("interni_doklady")
    INTERNI_DOKLADY("interni_doklady"),
    @XmlEnumValue("vydane_faktury")
    VYDANE_FAKTURY("vydane_faktury"),
    @XmlEnumValue("vydane_zalohove_faktury")
    VYDANE_ZALOHOVE_FAKTURY("vydane_zalohove_faktury");
    private final String value;

    IsdocAgendaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IsdocAgendaType fromValue(String v) {
        for (IsdocAgendaType c: IsdocAgendaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
