//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.filter;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stormware.schema.version_2.filter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stormware.schema.version_2.filter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestCashRegisterType }
     * 
     */
    public RequestCashRegisterType createRequestCashRegisterType() {
        return new RequestCashRegisterType();
    }

    /**
     * Create an instance of {@link RequestBankAccountType }
     * 
     */
    public RequestBankAccountType createRequestBankAccountType() {
        return new RequestBankAccountType();
    }

    /**
     * Create an instance of {@link RequestInvoiceType }
     * 
     */
    public RequestInvoiceType createRequestInvoiceType() {
        return new RequestInvoiceType();
    }

    /**
     * Create an instance of {@link RequestIntDocType }
     * 
     */
    public RequestIntDocType createRequestIntDocType() {
        return new RequestIntDocType();
    }

    /**
     * Create an instance of {@link RequestOrderType }
     * 
     */
    public RequestOrderType createRequestOrderType() {
        return new RequestOrderType();
    }

    /**
     * Create an instance of {@link DeleteOrderType }
     * 
     */
    public DeleteOrderType createDeleteOrderType() {
        return new DeleteOrderType();
    }

    /**
     * Create an instance of {@link RequestProdejkaType }
     * 
     */
    public RequestProdejkaType createRequestProdejkaType() {
        return new RequestProdejkaType();
    }

    /**
     * Create an instance of {@link RequestVyrobaType }
     * 
     */
    public RequestVyrobaType createRequestVyrobaType() {
        return new RequestVyrobaType();
    }

    /**
     * Create an instance of {@link RequestPrevodkaType }
     * 
     */
    public RequestPrevodkaType createRequestPrevodkaType() {
        return new RequestPrevodkaType();
    }

    /**
     * Create an instance of {@link RequestVoucherType }
     * 
     */
    public RequestVoucherType createRequestVoucherType() {
        return new RequestVoucherType();
    }

    /**
     * Create an instance of {@link RequestOfferType }
     * 
     */
    public RequestOfferType createRequestOfferType() {
        return new RequestOfferType();
    }

    /**
     * Create an instance of {@link RequestEnquiryType }
     * 
     */
    public RequestEnquiryType createRequestEnquiryType() {
        return new RequestEnquiryType();
    }

    /**
     * Create an instance of {@link RequestVydejkaType }
     * 
     */
    public RequestVydejkaType createRequestVydejkaType() {
        return new RequestVydejkaType();
    }

    /**
     * Create an instance of {@link RequestPrijemkaType }
     * 
     */
    public RequestPrijemkaType createRequestPrijemkaType() {
        return new RequestPrijemkaType();
    }

    /**
     * Create an instance of {@link RequestAccountancyType }
     * 
     */
    public RequestAccountancyType createRequestAccountancyType() {
        return new RequestAccountancyType();
    }

    /**
     * Create an instance of {@link RequestBankType }
     * 
     */
    public RequestBankType createRequestBankType() {
        return new RequestBankType();
    }

    /**
     * Create an instance of {@link RequestStoreType }
     * 
     */
    public RequestStoreType createRequestStoreType() {
        return new RequestStoreType();
    }

    /**
     * Create an instance of {@link RequestServiceType }
     * 
     */
    public RequestServiceType createRequestServiceType() {
        return new RequestServiceType();
    }

    /**
     * Create an instance of {@link RequestProductRequirementType }
     * 
     */
    public RequestProductRequirementType createRequestProductRequirementType() {
        return new RequestProductRequirementType();
    }

    /**
     * Create an instance of {@link RequestGroupStocksActionType }
     * 
     */
    public RequestGroupStocksActionType createRequestGroupStocksActionType() {
        return new RequestGroupStocksActionType();
    }

    /**
     * Create an instance of {@link RequestGroupStocksType }
     * 
     */
    public RequestGroupStocksType createRequestGroupStocksType() {
        return new RequestGroupStocksType();
    }

    /**
     * Create an instance of {@link FilterGroupStockType }
     * 
     */
    public FilterGroupStockType createFilterGroupStockType() {
        return new FilterGroupStockType();
    }

    /**
     * Create an instance of {@link RequestRegistrationNumberType }
     * 
     */
    public RequestRegistrationNumberType createRequestRegistrationNumberType() {
        return new RequestRegistrationNumberType();
    }

    /**
     * Create an instance of {@link RequestMovementType }
     * 
     */
    public RequestMovementType createRequestMovementType() {
        return new RequestMovementType();
    }

    /**
     * Create an instance of {@link RequestPaymentType }
     * 
     */
    public RequestPaymentType createRequestPaymentType() {
        return new RequestPaymentType();
    }

    /**
     * Create an instance of {@link RequestNumericalSeriesType }
     * 
     */
    public RequestNumericalSeriesType createRequestNumericalSeriesType() {
        return new RequestNumericalSeriesType();
    }

    /**
     * Create an instance of {@link RequestActionPriceType }
     * 
     */
    public RequestActionPriceType createRequestActionPriceType() {
        return new RequestActionPriceType();
    }

    /**
     * Create an instance of {@link RequestInventoryListsType }
     * 
     */
    public RequestInventoryListsType createRequestInventoryListsType() {
        return new RequestInventoryListsType();
    }

    /**
     * Create an instance of {@link RequestRecyclingContribType }
     * 
     */
    public RequestRecyclingContribType createRequestRecyclingContribType() {
        return new RequestRecyclingContribType();
    }

    /**
     * Create an instance of {@link RequestContractType }
     * 
     */
    public RequestContractType createRequestContractType() {
        return new RequestContractType();
    }

    /**
     * Create an instance of {@link RequestCategoryActionType }
     * 
     */
    public RequestCategoryActionType createRequestCategoryActionType() {
        return new RequestCategoryActionType();
    }

    /**
     * Create an instance of {@link FilterIDType }
     * 
     */
    public FilterIDType createFilterIDType() {
        return new FilterIDType();
    }

    /**
     * Create an instance of {@link RequestExtIdActionType }
     * 
     */
    public RequestExtIdActionType createRequestExtIdActionType() {
        return new RequestExtIdActionType();
    }

    /**
     * Create an instance of {@link RequestExtIdType }
     * 
     */
    public RequestExtIdType createRequestExtIdType() {
        return new RequestExtIdType();
    }

    /**
     * Create an instance of {@link FilterExtIdType }
     * 
     */
    public FilterExtIdType createFilterExtIdType() {
        return new FilterExtIdType();
    }

    /**
     * Create an instance of {@link FilterDocsType }
     * 
     */
    public FilterDocsType createFilterDocsType() {
        return new FilterDocsType();
    }

    /**
     * Create an instance of {@link SelectedNumbersType }
     * 
     */
    public SelectedNumbersType createSelectedNumbersType() {
        return new SelectedNumbersType();
    }

    /**
     * Create an instance of {@link SelectedCompanysType }
     * 
     */
    public SelectedCompanysType createSelectedCompanysType() {
        return new SelectedCompanysType();
    }

    /**
     * Create an instance of {@link SelectedIcoType }
     * 
     */
    public SelectedIcoType createSelectedIcoType() {
        return new SelectedIcoType();
    }

    /**
     * Create an instance of {@link RequestStockActionType }
     * 
     */
    public RequestStockActionType createRequestStockActionType() {
        return new RequestStockActionType();
    }

    /**
     * Create an instance of {@link RequestStockType }
     * 
     */
    public RequestStockType createRequestStockType() {
        return new RequestStockType();
    }

    /**
     * Create an instance of {@link FilterStocksType }
     * 
     */
    public FilterStocksType createFilterStocksType() {
        return new FilterStocksType();
    }

    /**
     * Create an instance of {@link RequestAddressBookActionType }
     * 
     */
    public RequestAddressBookActionType createRequestAddressBookActionType() {
        return new RequestAddressBookActionType();
    }

    /**
     * Create an instance of {@link RequestAddressBookType }
     * 
     */
    public RequestAddressBookType createRequestAddressBookType() {
        return new RequestAddressBookType();
    }

    /**
     * Create an instance of {@link FilterAdbsType }
     * 
     */
    public FilterAdbsType createFilterAdbsType() {
        return new FilterAdbsType();
    }

    /**
     * Create an instance of {@link RequestIndividualPriceType }
     * 
     */
    public RequestIndividualPriceType createRequestIndividualPriceType() {
        return new RequestIndividualPriceType();
    }

    /**
     * Create an instance of {@link FilterIndividualPriceType }
     * 
     */
    public FilterIndividualPriceType createFilterIndividualPriceType() {
        return new FilterIndividualPriceType();
    }

    /**
     * Create an instance of {@link RecordIsdocType }
     * 
     */
    public RecordIsdocType createRecordIsdocType() {
        return new RecordIsdocType();
    }

    /**
     * Create an instance of {@link RecordPrintType }
     * 
     */
    public RecordPrintType createRecordPrintType() {
        return new RecordPrintType();
    }

    /**
     * Create an instance of {@link FilterDocsDeleteType }
     * 
     */
    public FilterDocsDeleteType createFilterDocsDeleteType() {
        return new FilterDocsDeleteType();
    }

    /**
     * Create an instance of {@link UserFilterNameType }
     * 
     */
    public UserFilterNameType createUserFilterNameType() {
        return new UserFilterNameType();
    }

    /**
     * Create an instance of {@link RequestItemType }
     * 
     */
    public RequestItemType createRequestItemType() {
        return new RequestItemType();
    }

    /**
     * Create an instance of {@link FilterNumeciralSeriesType }
     * 
     */
    public FilterNumeciralSeriesType createFilterNumeciralSeriesType() {
        return new FilterNumeciralSeriesType();
    }

    /**
     * Create an instance of {@link FilterRegNumberType }
     * 
     */
    public FilterRegNumberType createFilterRegNumberType() {
        return new FilterRegNumberType();
    }

    /**
     * Create an instance of {@link FilterMovementType }
     * 
     */
    public FilterMovementType createFilterMovementType() {
        return new FilterMovementType();
    }

}
