//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.filter;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordPrintType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordPrintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="filter" type="{http://www.stormware.cz/schema/version_2/filter.xsd}filterIDType" minOccurs="0"/&gt;
 *         &lt;element name="userFilterName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="agenda" use="required" type="{http://www.stormware.cz/schema/version_2/filter.xsd}printAgendaType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordPrintType", propOrder = {

})
public class RecordPrintType {

    protected FilterIDType filter;
    protected String userFilterName;
    @XmlAttribute(name = "agenda", required = true)
    protected PrintAgendaType agenda;

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterIDType }
     *     
     */
    public FilterIDType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterIDType }
     *     
     */
    public void setFilter(FilterIDType value) {
        this.filter = value;
    }

    /**
     * Gets the value of the userFilterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFilterName() {
        return userFilterName;
    }

    /**
     * Sets the value of the userFilterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFilterName(String value) {
        this.userFilterName = value;
    }

    /**
     * Gets the value of the agenda property.
     * 
     * @return
     *     possible object is
     *     {@link PrintAgendaType }
     *     
     */
    public PrintAgendaType getAgenda() {
        return agenda;
    }

    /**
     * Sets the value of the agenda property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintAgendaType }
     *     
     */
    public void setAgenda(PrintAgendaType value) {
        this.agenda = value;
    }

}
