//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.09 at 03:15:47 PM CEST 
//


package cz.stormware.schema.version_2.filter;

import cz.stormware.schema.version_2.type.Boolean;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestGroupStocksActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestGroupStocksActionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.stormware.cz/schema/version_2/filter.xsd}requestGroupStocksType"&gt;
 *       &lt;attGroup ref="{http://www.stormware.cz/schema/version_2/filter.xsd}groupAttributeAction"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestGroupStocksActionType")
public class RequestGroupStocksActionType
    extends RequestGroupStocksType
{

    @XmlAttribute(name = "update")
    protected Boolean update;
    @XmlAttribute(name = "add")
    protected Boolean add;

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getUpdate() {
        if (update == null) {
            return Boolean.FALSE;
        } else {
            return update;
        }
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdate(Boolean value) {
        this.update = value;
    }

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAdd() {
        if (add == null) {
            return Boolean.FALSE;
        } else {
            return add;
        }
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAdd(Boolean value) {
        this.add = value;
    }

}
